import { Product, PetParentReview } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: '알래스카 자연산 생연어 & 유기농 슈퍼베리 그레인프리 1.5kg',
    category: 'dog',
    badge: '시그니처 베스트',
    subBadge: '눈물·피부 케어',
    badgeType: 'signature',
    rating: 4.9,
    reviewCount: 1840,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCCzvok_5oRJBYQQZTxrXaz4bbtp0WWUGjfCxAsDJZ3HELh2XWwUk1-9TK_0iYUAn1NVsAC62D9n7qgBevK29XzxP68tXnitOlzR7zxkCK44lf0fGDVaCXZVkI9Cods70mbWVA33DWmrMpSADqXhqu-xfh4mipOOKr4q3kOu7103mVURz_uv6QXILH7OI4tDr8TzGeVOoViSxU0Y1JWgbA61OoG06qjgcs-BcRPAzqvgkAKgHFkEOAN',
    kibbleBadge: '키블 8mm 스몰바이트',
    tags: ['생연어 65%', '오메가3 3.2%', '루테인 강화'],
    discountRate: 15,
    originalPrice: 45000,
    price: 38250,
    unitPrice: '100g당 ₩2,550 | 정기구독 추가할인 가능',
    dosageTip: '소형견 기준 하루 75~85g 분할 급여',
    isPopular: true,
    allergySafe: true,
  },
  {
    id: 'prod-2',
    name: '무항생제 오리고기 & 뉴질랜드 초록입홍합 동결건조 생식 400g',
    category: 'barf',
    badge: '동결건조 BARF',
    subBadge: '슬개골 관절강화',
    badgeType: 'barf',
    rating: 4.95,
    reviewCount: 920,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAZLNalz3n3gnCwnCPnauLV6TQuMD8rdrDw5DFrMPtpHQdNK6UthGZ7JrEH0YFHL39rCWee7IZGQbMwNfTKallfqekC2ptznaNWlSrqHvd7cRa-_KKIJMsVWk44qUG4SigJu6SPQwikDsjU1iJoOTdLy-o8BjI2hs622jODY4z5KLlY904PPF4q_OpyeQPIJaV73gZ_11ZuoHuL67w85xoPkZHG7lLGTY7mzkpKIcOJVb8I2nUm6NdB',
    kibbleBadge: '15mm 큐브 블록',
    tags: ['통오리 80%', '초록입홍합 10%', '물에 불리는 화식'],
    discountRate: 12,
    originalPrice: 36000,
    price: 31680,
    unitPrice: '100g당 ₩7,920 | 미온수에 3분 불려 급여',
    dosageTip: '미온수 1:1 비율로 불려 급여 권장',
    isPopular: true,
    allergySafe: true,
  },
  {
    id: 'prod-3',
    name: '노르웨이 생연어 & 크랜베리 유리너리 스트루바이트 케어 1.2kg',
    category: 'cat',
    badge: '반려묘 전용',
    subBadge: '유리너리 케어',
    badgeType: 'cat',
    rating: 4.88,
    reviewCount: 640,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAFE62rRhv1sUbvyXAo8110JOuarAXkWmvYb0q43Sld5nRFwgyLxIi7_Sxcj19PUG1bIK_9aXAVao2lMTGzrpPrB8OoxuhOuDxwg1iwz6YE1NbKP5bicDIaIHdd0PrtnDcqw1W8XKFRPCMJ3a7SsCZvH5--KEVOZXCmk_ebx50L4Me7_QyWbzJIo9Wgxa7dDCrMVaXIDoLA5XG6Zh2Q_SbHEWXC14HKPyWF3SA1cCi7Njd4bjFgCFsj',
    kibbleBadge: '키블 7mm 도넛형',
    tags: ['타우린 2,500mg', 'pH 6.2~6.4 조절', '요로결석 예방'],
    discountRate: 10,
    originalPrice: 39000,
    price: 35100,
    unitPrice: '100g당 ₩2,925 | 고양이 기호도 96% 만족',
    dosageTip: '신선한 음수와 함께 하루 50~65g 급여',
    isPopular: false,
    allergySafe: true,
  },
  {
    id: 'prod-4',
    name: '300억 투입 생유산균 & 소화효소 포스트바이오틱스 30포',
    category: 'supplement',
    badge: '처방 영양제',
    subBadge: '장·면역 특허',
    badgeType: 'supplement',
    rating: 4.92,
    reviewCount: 2110,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBjQhugRoqRkwAIqzG4Y_3sEg_TtJ2MGFwqBYXSU6FQwYS5aeDgMntZiod1Bz5mpwpnskiIcprMlM39XXqqiGr9glQQModSBLwC0lrIr6CQn4spVneUJStOTXQG1uNz0OI9OwKPF5qeORGD81VdxuRQbxf76O-dNfwizyNYf4yk3nJ3-kZhKQmr4Ti97rhQq_wvfQ6TxgH5966lJEBHOtZd9MeVuN7SaVj5lgxR6G0l3oA5v7Mkfb1X',
    kibbleBadge: '1포 2g 개별스틱',
    tags: ['300억 CFU 투입', '변냄새 72% 감소', '알루미늄 4중 차광'],
    discountRate: 20,
    originalPrice: 29000,
    price: 23200,
    unitPrice: '1포당 ₩773 | 30일분 집중 장 면역 케어',
    dosageTip: '식사 전 미온수나 사료 위에 1포 뿌려 급여',
    isPopular: true,
    allergySafe: true,
  },
];

export const INITIAL_REVIEWS: PetParentReview[] = [
  {
    id: 'rev-1',
    petName: '말티푸 구름이 (3세)',
    age: '3세',
    breed: '말티푸',
    productFed: '생연어 & 슈퍼베리 1.5kg 급여 3개월 차',
    rating: 5,
    content: '"어릴 때부터 눈물자국이 붉게 번져서 온갖 사료 다 바꿔봤는데, 포우즈 연어 사료로 바꾸고 3주 지나니까 눈 밑 털이 하얗게 자라나기 시작했어요! 냄새도 역한 비린내가 아니라 고소한 생선 냄새라 밥그릇 싹싹 비웁니다."',
    author: '이*서 님 (정기구독 고객)',
    likes: 142,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCwUSbBmvfbtXUMJbhATxcLmZgPUBZ1beko46Pn8N1VZHBdRprzh_PSkExlQl2Jj-jWP2MsQPoRkAxoVMQXprDQdmLjOtdH6C4vOszdpqEvUD5VMqnof0wPBnkKnoWoACapjwCiM5E_fBzcvJWRmXjXnz6kipNjn3IzpVyJdKR37314PeeLbk3oaZ4c3p1bwAiiRJlHLchbtoMiOrKYoa38HGoQYeGgBEihbxMr02vTrhoJqFyTekaY',
  },
  {
    id: 'rev-2',
    petName: '포메라니안 탄이 (4세)',
    age: '4세',
    breed: '포메라니안',
    productFed: '동결건조 오리 & 초록입홍합 급여',
    rating: 5,
    content: '"슬개골 탈구 2기 진단받고 산책도 꺼려해서 속상했는데, 초록입홍합 동결건조 생식을 미온수에 불려 매일 줬더니 관절 삐걱이는 소리도 안 나고 다시 활발하게 뛰어놀아요. 화식처럼 촉촉해서 음수량 채우기도 너무 좋습니다."',
    author: '박*우 님 (재구매 5회차)',
    likes: 98,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCAhsy9bvuP6p0ZWKic7KhH5ugiAZFW6cnTu8m46_Rlo6N7W7giF36_CuTdEljlikHut8zB6-9iEUlU1PNsZvdOfKifYH8LAkoDZWvkD5M9tRy9XujdHL61aqAwA7FviZriFtdn0RYluDW-OdQP0Z8NLYu60Cd2tQD4WPPXq988Yy3_7WqV_3bkkY-VNlpao9Qr8SmG_e5qF2C-mD2FzH36Vp5sPMfGIlPCpdOiVVLdyQqVkfvInfaz',
  },
  {
    id: 'rev-3',
    petName: '러시안블루 루나 (2세)',
    age: '2세',
    breed: '러시안블루',
    productFed: '노르웨이 생연어 유리너리 1.2kg 급여',
    rating: 5,
    content: '"수컷 냥이라 방광염과 스트루바이트 결석 걱정이 컸는데, 크랜베리와 타우린이 함께 들어간 이 사료 먹이고 감자 크기가 눈에 띄게 커졌어요! 키블 크기도 7mm 도넛형이라 토하지 않고 잘 씹어먹네요."',
    author: '정*민 님 (정기구독 고객)',
    likes: 116,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAximrg1p7dfWJIF2wmlWGW1DRym21HgGB8I6nFzHhwJiTnMrEUQMHE63nuNwxanBcJYQah7-R9KkbiOrL-C_HSTpTF9t_tRCvfzp6CyOt6vvnjOm3AM3yajJArR191TMgSF5NXdSubTJ0TJZSiKQkqgr5IHGE9x7zw0Nwk32gLlW3xmgJP19nzKxEy0GzS5Facv-6-r0wrL8PBXRiwh7dIebNk-tpSPLC1xEgnn74flBXL1PZUVIm8',
  },
];
