import { Product, PetParentReview } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: '알래스카 자연산 생연어 & 슈퍼베리 그레인프리 1.5kg',
    category: 'dog',
    badge: '시그니처 베스트',
    subBadge: '눈물·피부 케어',
    badgeType: 'signature',
    rating: 4.9,
    reviewCount: 1840,
    image: '/demo-media/paws-tail/paws-tail-08.jpg',
    kibbleBadge: '키블 8mm 스몰바이트',
    tags: ['생연어 65%', '오메가3 3.2%', '루테인 강화'],
    discountRate: 15,
    originalPrice: 45000,
    price: 38250,
    unitPrice: '100g당 ₩2,550 | 정기구독 추가할인 가능',
    dosageTip: '소형견 기준 하루 75~85g 분할 급여',
    isPopular: true,
    allergySafe: true,
    lifeStage: 'adult',
    clinicalTarget: 'allergies',
    grainFree: true,
    chickenFree: true,
  },
  {
    id: 'prod-2',
    name: '오리고기 & 뉴질랜드 초록입홍합 동결건조 생식 400g',
    category: 'barf',
    badge: '동결건조 BARF',
    subBadge: '슬개골 관절강화',
    badgeType: 'barf',
    rating: 4.95,
    reviewCount: 920,
    image: '/demo-media/paws-tail/paws-tail-02.jpg',
    kibbleBadge: '15mm 큐브 블록',
    tags: ['통오리 80%', '초록입홍합 10%', '물에 불리는 화식'],
    discountRate: 12,
    originalPrice: 36000,
    price: 31680,
    unitPrice: '100g당 ₩7,920 | 미온수에 3분 불려 급여',
    dosageTip: '미온수 1:1 비율로 불려 급여 권장',
    isPopular: true,
    allergySafe: true,
    lifeStage: 'allStage',
    clinicalTarget: 'joints',
    grainFree: true,
    chickenFree: true,
  },
  {
    id: 'prod-3',
    name: '노르웨이 생연어 & 크랜베리 유리너리 스트루바이트 케어 1.2kg',
    category: 'cat',
    badge: '반려묘 전용',
    subBadge: '유리너리 케어',
    badgeType: 'cat',
    rating: 4.88,
    reviewCount: 640,
    image: '/demo-media/paws-tail/paws-tail-01.jpg',
    kibbleBadge: '키블 7mm 도넛형',
    tags: ['타우린 2,500mg', 'pH 6.2~6.4 조절', '요로계 케어 설계'],
    discountRate: 10,
    originalPrice: 39000,
    price: 35100,
    unitPrice: '100g당 ₩2,925 | 기호도 테스트 결과 (예시)',
    dosageTip: '신선한 음수와 함께 하루 50~65g 급여',
    isPopular: false,
    allergySafe: true,
    lifeStage: 'adult',
    clinicalTarget: 'urinary',
    grainFree: true,
    chickenFree: true,
  },
  {
    id: 'prod-4',
    name: '생유산균 & 소화효소 포스트바이오틱스 30포',
    category: 'supplement',
    badge: '처방 영양제',
    subBadge: '장·면역 집중',
    badgeType: 'supplement',
    rating: 4.92,
    reviewCount: 2110,
    image: '/demo-media/paws-tail/paws-tail-04.jpg',
    kibbleBadge: '1포 2g 개별스틱',
    tags: ['300억 CFU 투입 (예시)', '변냄새 케어 (예시)', '알루미늄 4중 차광'],
    discountRate: 20,
    originalPrice: 29000,
    price: 23200,
    unitPrice: '1포당 ₩773 | 30일분 집중 장 면역 케어',
    dosageTip: '식사 전 미온수나 사료 위에 1포 뿌려 급여',
    isPopular: true,
    allergySafe: true,
    lifeStage: 'allStage',
    clinicalTarget: 'gut',
    // 기호성 코팅에 곡물 유래 배지와 닭고기 분말이 들어간 설정 — 두 칩이 실제로 목록을 바꾸도록 남겨 둔다
    grainFree: false,
    chickenFree: false,
  },
];

export const INITIAL_REVIEWS: PetParentReview[] = [
  {
    id: 'rev-1',
    petName: '말티푸 구름이 (3세)',
    age: '3세',
    breed: '말티푸',
    productFed: '생연어 & 슈퍼베리 1.5kg 급여 3개월 차',
    rating: 5,
    content: '"입이 짧아서 사료를 몇 번이나 바꿔봤는데, 포우즈 연어 사료는 첫날부터 밥그릇을 싹싹 비웠어요. 냄새도 역한 비린내가 아니라 고소한 생선 냄새라 봉투를 열 때 부담이 없고, 8mm 스몰바이트라 우리 아이 입 크기에 딱 맞습니다."',
    author: '이*서 님 (정기구독 고객)',
    likes: 142,
    image: '/demo-media/paws-tail/paws-tail-09.jpg',
  },
  {
    id: 'rev-2',
    petName: '포메라니안 탄이 (4세)',
    age: '4세',
    breed: '포메라니안',
    productFed: '동결건조 오리 & 초록입홍합 급여',
    rating: 5,
    content: '"동결건조라 보관이 편하고, 미온수에 3분만 불리면 화식처럼 촉촉해져서 급여 준비가 정말 간단해요. 물을 잘 안 먹는 아이라 늘 걱정이었는데 불려 주면 그릇을 국물까지 비웁니다. 큐브 블록이라 손에 부스러기가 묻지 않는 것도 좋아요."',
    author: '박*우 님 (재구매 5회차)',
    likes: 98,
    image: '/demo-media/paws-tail/paws-tail-07.jpg',
  },
  {
    id: 'rev-3',
    petName: '러시안블루 루나 (2세)',
    age: '2세',
    breed: '러시안블루',
    productFed: '노르웨이 생연어 유리너리 1.2kg 급여',
    rating: 5,
    content: '"기존에 먹던 사료를 갑자기 안 먹어서 바꿔봤는데 기호도가 훨씬 좋아요. 7mm 도넛형이라 급하게 삼키지 않고 오독오독 잘 씹어 먹고, 지퍼백이라 개봉 후 눅눅해지지 않아서 마지막 한 알까지 바삭합니다."',
    author: '정*민 님 (정기구독 고객)',
    likes: 116,
    image: '/demo-media/paws-tail/paws-tail-03.jpg',
  },
];
