export type GalleryCategoryId =
  | 'corporate'
  | 'commerce'
  | 'medical'
  | 'interior'
  | 'architecture'
  | 'saas'
  | 'manufacturing';

export interface GalleryCategoryMeta {
  id: GalleryCategoryId;
  number: string;
  name: string;
  engName: string;
  description: string;
  badge: string;
}

export interface GalleryProject {
  id: string;
  title: string;
  client: string;
  category: GalleryCategoryId;
  categoryName: string;
  summary: string;
  description: string;
  thumbnailUrl: string;
  liveDemoUrl?: string;
  externalUrl?: string;
  techStack: string[];
  period: string;
  year: string;
  badge?: string;
  highlights: string[];
}

export const GALLERY_CATEGORIES: GalleryCategoryMeta[] = [
  {
    id: 'corporate',
    number: '01',
    name: '기업 랜딩 · 스타트업 · 브랜드 플래그십',
    engName: 'Corporate & Brand Flagship',
    description: '글로벌 투자 유치와 엔터프라이즈 수주를 이끄는 테크 스타트업 IR 랜딩, 상장사 및 중견기업 공식 플래그십 사이트입니다.',
    badge: '글로벌 IR 특화',
  },
  {
    id: 'commerce',
    number: '02',
    name: '쇼핑몰 · 이커머스 · D2C 브랜드',
    engName: 'E-Commerce & D2C Brands',
    description: '브랜드 고유의 철학을 담은 비주얼 스토리텔링과 초고속 체크아웃, 정기구독 빌링을 지원하는 프리미엄 브랜드 커머스입니다.',
    badge: '고전환 결제 UX',
  },
  {
    id: 'medical',
    number: '03',
    name: '병의원 · 메디컬 · 치과 클리닉',
    engName: 'Medical & Healthcare Clinic',
    description: '의료진의 학술 전문성과 임상 신뢰도를 극대화하고, 네이버 예약 연동과 비급여 항목 수가 투명 공개로 신환 내원을 촉진하는 전문 클리닉 솔루션입니다.',
    badge: '임상 신뢰 · 신환 유치',
  },
  {
    id: 'interior',
    number: '04',
    name: '인테리어 · 공간 디자인 · 하이엔드',
    engName: 'Interior & Spatial Design',
    description: '자연석과 원목의 질감, 절제된 세리프 타이포그래피로 공간의 격조를 극대화한 최고급 주거·상업 공간 스튜디오 웹사이트입니다.',
    badge: '하이엔드 감성',
  },
  {
    id: 'architecture',
    number: '05',
    name: '건축 · 종합건설 · 토목엔지니어링',
    engName: 'Architecture & Construction',
    description: '종합건설사, 설계사무소, 플랜트·물류센터의 수주 경쟁력을 극대화하는 시공 실적 아카이브와 공법 소개 디지털 브로슈어입니다.',
    badge: '대형 시공 수주',
  },
  {
    id: 'saas',
    number: '06',
    name: 'SaaS · 전자서약 · B2B 플랫폼',
    engName: 'B2B SaaS & Digital Platforms',
    description: '전자서명법에 근거한 카카오 모바일 전자서명부터 300종 법정 서식 에디터, 엔지니어링 매칭 및 단계별 안심 기성 정산 플랫폼입니다.',
    badge: '자체 직영 운영',
  },
  {
    id: 'manufacturing',
    number: '07',
    name: '제조 · 스마트팩토리 · 소재공정',
    engName: 'Manufacturing & Smart Factory',
    description: '수기 엑셀 장부를 실시간 통계 관리도(SPC), 수율 워터폴 분석, 4단계 로트 계보 역추적 시스템으로 디지털 전환한 엔터프라이즈 솔루션입니다.',
    badge: '정밀 제조 데이터',
  },
];

export const GALLERY_PROJECTS: GalleryProject[] = [
  // ─── 01. 제조 (Manufacturing) ─────────────────────────────────
  {
    id: 'wonik-qnc-semiconductor-quartz',
    title: '반도체 쿼츠웨어 & 정밀 세라믹 기업 플래그십',
    client: '반도체 쿼츠웨어 · 정밀 세라믹 제조사',
    category: 'manufacturing',
    categoryName: '제조 · 반도체 소재부품',
    summary: '4대 사업부 쇼케이스, 창립 기념 영상 상영관 및 주가·공시 IR 허브',
    description: '반도체 식각·확산 공정 핵심 소재인 쿼츠웨어·정밀 세라믹 제조사를 상정하고 만든 플래그십 화면입니다. 4대 핵심 사업(쿼츠·세라믹·세정·옵틱) 인터랙티브 도면 및 쇼케이스, 창립 기념 영상 상영관, 주가 차트 화면 및 신규 협력제안 포털을 담았습니다.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDgg1CFsX4Rlv7v8iswdosWchI-qMhyrD7vwnGmzOaR6P-3sCJD0XKtk3YCJebSRHSgrWQfTr1SQN79YTb7LobEF40hJaWrjcIyvbZyuxBi30x9cCYDsUv2XQsfpBCr_QHZ5qK1L1koYU4K9vg0r_8xrlGh9lhAfNHaUpRpM5KhGQ8Rfl3EBfuB-BbnFEs5Y1dunYaSmlNz5v4jkAwBK8m09fzboo4jrX0KCGkod1YWjeDPjqdaShEl',
    liveDemoUrl: '/demo/wonik-qnc',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', 'PR Film Theater', 'IR Dashboard'],
    period: '3주',
    year: '2026',
    badge: '기업 IR 허브',
    highlights: [
      '300mm 웨이퍼 식각·확산 쿼츠웨어 4대 사업부 인터랙티브 쇼케이스',
      '창립 기념 홍보 영상 극장 모달 및 UHD 챕터 네비게이션',
      '주가·시가총액·외국인보유율 IR 화면 및 전자공시 목록 구성',
      '신규 협력사 제안, 공장 견학 예약, 4개국어(KR/EN/CN/JP) 대응',
    ],
  },
  {
    id: 'hysfa-semiconductor-scada',
    title: '반도체 FA & 초고순도 가스 시스템 기업 웹사이트',
    client: '반도체 FA 장비 · 초고순도 가스 시스템 기업',
    category: 'manufacturing',
    categoryName: '제조 · 반도체 장비',
    summary: '3대 사업부 쇼케이스, 5단계 품질 파이프라인 및 온라인 견적 접수 화면',
    description: '반도체 공정 자동화(FA) 설비, 초고순도(UHP) 가스 공급 인프라, 스마트 제어 S/W를 함께 다루는 장비 기업을 상정하고 만든 공식 웹사이트 화면입니다. 연혁 아카이브, 5단계 전수 검사 QA 파이프라인, 온라인 견적 접수 화면을 담았습니다.',
    thumbnailUrl: '/hysfa/sub205_img01.jpg',
    liveDemoUrl: '/demo/hysfa',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', '5-Stage QA Pipeline', 'Bilingual (KR/EN)'],
    period: '4주',
    year: '2026',
    badge: '품질 파이프라인',
    highlights: [
      '반도체 FA 장비, 초고순도(UHP) 가스 배관 및 제어 S/W 3대 핵심 사업부 쇼케이스',
      '품질 인증 소개 및 연혁 인터랙티브 아카이브',
      '원자재 수입검사부터 헬륨 리크·72시간 신뢰성 시운전까지 5단계 전수 검사 파이프라인',
      '엔지니어링 온라인 견적 접수 위저드 채번 및 글로벌 다국어(KR/EN) 원클릭 전환',
    ],
  },
  {
    id: 'lithium-foil-spc',
    title: '리튬박 공정 데이터 모니터링 플랫폼',
    client: '2차전지 배터리 소재 제조사',
    category: 'manufacturing',
    categoryName: '제조 · 소재공정',
    summary: '슬리팅 롤 일지 입력 즉시 7대 불순물 통계 관리도와 4단계 로트 계보가 동기화되는 스마트 제조 플랫폼',
    description: '엑셀 수기 장부로 관리되던 리튬박 현장 일지를 웹 기반 실시간 엔터프라이즈 모니터링 시스템으로 전환했습니다. 7대 미량 불순물(Fe, Cu, Ni 등) ICP 통계 관리도(SPC), 12주 수율 워터폴 분석, 잉곳부터 슬리팅까지 완벽한 로트(Lot) 계보 역추적 엔진을 갖추고 있습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '/demo/lithium-foil',
    techStack: ['Next.js 16', 'React 19', 'TypeScript', 'Tailwind CSS v4', 'Custom SPC Charts'],
    period: '3주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      '12주 시뮬레이션 데이터 기반 실시간 통계 관리도 (Control Chart)',
      '슬리팅 현장 롤 일지 입력 즉시 전역 데이터 실시간 갱신',
      '잉곳-원료-슬리팅 4단계 로트(Lot) 계보 완벽 역추적',
      '관리한계선(USL/UCL) 자동 계산 및 불량 경보 알고리즘',
    ],
  },
  {
    id: 'cathode-mixing-scada',
    title: '2차전지 양극재 분체 배합 SCADA 시스템',
    client: '정밀 화학소재 엔터프라이즈',
    category: 'manufacturing',
    categoryName: '제조 · 스마트팩토리',
    summary: '고속 혼합기 8기 동시 계측 및 온도·압력·RPM 이상 감지 웹 관제 콘솔',
    description: '고용량 양극재 제조 라인의 분체 배합 공정을 초당 10회 고속 폴링하여 실시간 관리자 화면에 렌더링하는 엔터프라이즈 웹 대시보드입니다. 배치별 배합비 공차 초과 시 즉각 카카오 알림톡 및 경고 팝업을 발생시킵니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1565043666747-69f6646db940?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'WebSockets', 'Chart.js', 'PostgreSQL', 'Tailwind CSS'],
    period: '4주',
    year: '2025',
    badge: '대규모 관제',
    highlights: [
      '초당 10회 고속 데이터 스트리밍 렌더링',
      '8기 분체 믹서 실시간 상태 및 RPM 모니터링',
      '배치별 투입 원료 바코드 이력 추적',
      '이상 징후 발생 즉시 관리자 원격 비상 정지 트리거',
    ],
  },
  {
    id: 'semiconductor-clean-spc',
    title: '반도체 웨이퍼 세정 공정 SPC 통계 플랫폼',
    client: '반도체 전공정 부품사',
    category: 'manufacturing',
    categoryName: '제조 · 정밀전자',
    summary: '세정액 약액 농도 및 파티클 카운트 자동 분석 수율 관리 시스템',
    description: '클린룸 내 웨이퍼 세정 약품의 화학 조성비와 잔류 파티클 통계를 웨이퍼 랏(Lot) 단위로 실시간 수집하여, 공정 능력 지수(Cp, Cpk)를 자동 산출하는 웹 플랫폼입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Python FastAPI', 'TypeScript', 'Tailwind CSS', 'Highcharts'],
    period: '4주',
    year: '2025',
    badge: 'Cpk 수율 관리',
    highlights: [
      'Cpk 공정 능력 지수 실시간 자동 계산',
      '웨이퍼 랏별 파티클 히트맵 인터랙티브 뷰어',
      '케미컬 약액 교체 시점 예측 AI 알림',
    ],
  },
  {
    id: 'copper-foil-r2r',
    title: '동박 Roll-to-Roll 인라인 결함 감지 웹 뷰어',
    client: '초극박 동박 제조 전문기업',
    category: 'manufacturing',
    categoryName: '제조 · 롤투롤공정',
    summary: '초속 15m 고속 주행 롤 표면 핀홀 및 주름 실시간 좌표 맵핑 콘솔',
    description: '광학 비전 카메라 16대에서 전송되는 동박 표면 결함 좌표(X, Y, 면적)를 롤 길이 1,000m 단위로 웹 캔버스에 실시간 핀포인팅하여 재단 시 불량 구간을 자동 마킹합니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1580983218765-f663bec07b37?auto=format&fit=crop&w=800&q=80',
    techStack: ['React', 'HTML5 Canvas', 'Tailwind CSS', 'TypeScript', 'Node.js'],
    period: '3주',
    year: '2025',
    badge: '인라인 비전',
    highlights: [
      'HTML5 고성능 캔버스 기반 초당 60fps 결함 맵핑',
      '핀홀·스크래치·주름 결함 유형별 필터링',
      '슬리팅 재단 최적화 컷팅 플랜 자동 생성',
    ],
  },
  {
    id: 'press-molding-iot',
    title: '자동차 부품 정밀 프레스 사출 IoT 모니터링',
    client: '티어1 자동차 샤시 부품사',
    category: 'manufacturing',
    categoryName: '제조 · 프레스가공',
    summary: '금형 온도 편차 및 프레스 타격 하중 톤수 실시간 계측 모니터링',
    description: '1,200톤 프레스 설비 6기의 타격 하중 센서와 금형 온도 데이터를 연동하여, 금형 마모와 크랙을 사전에 방지하는 예지 정비 대시보드를 구축했습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'MQTT', 'Chart.js'],
    period: '3주',
    year: '2024',
    badge: 'IoT 예지정비',
    highlights: [
      '하중 로드셀 센서 실시간 피크 톤수 트래킹',
      '금형 수명 타수 카운터 및 마모 주기 예측',
      '작업자별 생산 목표치 대비 실시간 달성률 게이지',
    ],
  },
  {
    id: 'chemical-reactor-portal',
    title: '정밀화학 배치 반응기 제어 & 생산 이력 포털',
    client: '특수 기능성 폴리머 제조사',
    category: 'manufacturing',
    categoryName: '제조 · 화학플랜트',
    summary: '반응조 12기 승온·냉각 사이클 실시간 기록 및 시험성적서 자동 발행',
    description: '화학 반응조별 교반 속도, 승온 프로파일, 압력 변화를 디지털 레코더로 자동 기록하고 출하 시험 성적서(COA)를 원클릭 PDF로 자동 생성합니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'TypeScript', 'PDFKit', 'Tailwind CSS', 'PostgreSQL'],
    period: '4주',
    year: '2024',
    badge: 'COA 성적서 자동화',
    highlights: [
      '반응 프로파일 타임라인 비교 오버레이',
      'COA 시험성적서 원클릭 PDF 자동 발행',
      '화학물질관리법(화관법) 준수 로그 저장',
    ],
  },

  // ─── 02. 인테리어 (Interior) ─────────────────────────────────
  {
    id: 'atelier-vaucluse',
    title: '아뜰리에 보클루즈 (ATELIER VAUCLUSE)',
    client: '건축 · 인테리어 디자인 스튜디오',
    category: 'interior',
    categoryName: '인테리어 · 건축',
    summary: '미니멀 세리프와 자연석 샌드 웜톤의 프렌치 모더니즘 하이엔드 건축·인테리어 스튜디오 웹사이트',
    description: '화려한 치장보다 천연 트래버틴과 미장 회벽, 훈증 오크의 물성을 앞세운 최고급 건축 인테리어 에이전시의 브랜드 웹사이트입니다. 공간 철학 3대 축 소개, 반응형 프로젝트 아카이브 및 필터링, 1:1 프라이빗 공간 컨설팅 예약 위저드 시스템을 탑재했습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '/demo/atelier-vaucluse',
    techStack: ['Next.js 16', 'Tailwind CSS v4', 'TypeScript', 'Editorial Grid', 'Modal Booking'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      '공간 철학 및 4단계 건축 프로세스 인터랙션',
      '고해상도 건축 프로젝트 갤러리 & 동적 필터',
      '프라이빗 1:1 고객 상담 예약 위저드',
      '천연 트래버틴/오크 등 마감재 디지털 라이브러리',
    ],
  },
  {
    id: 'hannam-penthouse',
    title: 'HAUS & SPACE (하이엔드 펜트하우스 리노베이션)',
    client: '하이엔드 프라이빗 인테리어 아키텍처 랩',
    category: 'interior',
    categoryName: '인테리어 · 주거공간',
    summary: '빛과 그림자의 여백을 담은 최고급 100평형 펜트하우스 시공 포트폴리오',
    description: '도심 속 안식처를 지향하는 최고급 펜트하우스 전용 포트폴리오 사이트로, 시공 전 3D 렌더링과 완공 후 8K 실물 사진을 인터랙티브 슬라이더로 비교 감상할 수 있습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '/demo/haus-space',
    techStack: ['Next.js 16', 'Tailwind CSS v4', 'TypeScript', 'Before & After Slider', '360 VR Tour'],
    period: '2주',
    year: '2025',
    badge: '실물 라이브 데모',
    highlights: [
      'Before & After 시공 전후 비교 인터랙티브 슬라이더',
      '수입 주방가구 및 조명 스펙 인터랙티브 핀 마킹',
      '공간별 파노라마 360 가상 투어 뷰어 연동',
    ],
  },
  {
    id: 'seongsu-flagship-showroom',
    title: '성수 플래그십 쇼룸 & 복합문화공간 디자인',
    client: '공간 브랜딩 크리에이티브 그룹',
    category: 'interior',
    categoryName: '인테리어 · 상업공간',
    summary: '노출 콘크리트와 스틸, 식생의 조화를 담은 상업 공간 브랜딩 웹사이트',
    description: '브랜드 팝업과 플래그십 쇼룸을 전문으로 설계하는 스튜디오의 프로젝트 아카이브로, 공간 기획부터 브랜드 아이덴티티, 가구 제작까지의 전 과정을 매거진 스타일로 소개합니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'Framer Motion', 'TypeScript'],
    period: '2주',
    year: '2025',
    badge: '상업 공간 브랜딩',
    highlights: [
      '매거진 스타일 에디토리얼 레이아웃',
      '공간별 방문객 동선 인터랙티브 맵',
      '클라이언트 브랜드 협업 히스토리 쇼케이스',
    ],
  },
  {
    id: 'bundang-workspace',
    title: '테크 스타트업 분당 사옥 스마트 오피스',
    client: '오피스 전문 인테리어 그룹',
    category: 'interior',
    categoryName: '인테리어 · 업무공간',
    summary: '몰입과 협업을 유도하는 500석 규모 IT 기업 사옥 공간 설계 포트폴리오',
    description: '하이브리드 워크 환경을 고려한 폰부스, 라운지, 타운홀 미팅 공간의 음향 흡음 설계와 조도 제어 시스템을 인터랙티브하게 안내하는 웹사이트입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript'],
    period: '2주',
    year: '2025',
    badge: '스마트 오피스',
    highlights: [
      '500석 규모 층별 공간 조닝 다이어그램 인터랙션',
      '모듈형 회의실 예약 키오스크 UI 목업 연동',
      '친환경 LEED 인증 자재 아카이브',
    ],
  },
  {
    id: 'jeju-stone-stay',
    title: '제주 애월 돌담 프리미엄 독채 스테이',
    client: '스테이 기획 & 건축 디자인 랩',
    category: 'interior',
    categoryName: '인테리어 · 숙박공간',
    summary: '제주 현무암과 노천 히노끼탕의 감성을 담은 부티크 스테이 브랜드 웹',
    description: '제주 자연을 온전히 담아낸 독채 풀빌라의 공간 포트폴리오로, 실시간 객실 예약 시스템 연동 및 계절별 채광 변화를 영상으로 담아냈습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'Booking API'],
    period: '2주',
    year: '2024',
    badge: '부티크 스테이',
    highlights: [
      '감성적 비디오 백그라운드 스트리밍',
      '객실별 실시간 예약 캘린더 연동',
      '주변 제주 로컬 명소 큐레이션 지도',
    ],
  },
  {
    id: 'cheongdam-beauty-lounge',
    title: '청담동 프라이빗 웰니스 & 뷰티 라운지',
    client: '뷰티 메디컬 인테리어 스튜디오',
    category: 'interior',
    categoryName: '인테리어 · 뷰티/의료',
    summary: '곡면 미장벽과 간접 조명으로 완성한 프라이빗 VIP 케어 공간',
    description: '철저한 프라이버시 보호를 위한 1인 VIP 룸 동선 분리와 무영등 조도 설계를 강조한 하이엔드 뷰티 메디컬 공간 프로젝트입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript'],
    period: '2주',
    year: '2024',
    badge: 'VIP 프라이빗',
    highlights: [
      '곡선형 벽체 시공 공법 상세 소개',
      '1인 VIP 케어룸 동선 설계 시뮬레이션',
      '상담 예약 폼과 카카오 채널 실시간 연동',
    ],
  },

  // ─── 03. 건축 (Architecture) ─────────────────────────────────
  {
    id: 'sodamjae-hanok-architecture',
    title: '전통한옥 & 프리미엄 중목구조 건축공방',
    client: '전통한옥 · 중목구조 전문 건축공방',
    category: 'architecture',
    categoryName: '건축 · 현대한옥/주거',
    summary: '25년 도편수 직영 전통 결구(사개맞춤) 공법과 패시브 삼중창호 단열을 융합한 프리미엄 한옥 스튜디오',
    description: '100년 목재 자연 건조 노하우, 못을 쓰지 않는 전통 사개맞춤 결구의 구조미 위에 최고 등급 시스템 삼중창호와 현대식 지열·단열 설비를 더한 프리미엄 한옥 건축공방의 공식 웹사이트입니다. 전국 68채 완공작 아카이브, 도편수 철학, 5단계 시공 로드맵 및 1:1 맞춤 견적 신청 위저드를 탑재했습니다.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD_PpesrIFiVF4zFREwOcLQM-SdxMeXTGAlM4AyMaAoLdhb74A4OKHLdKt9pUUP3z3nC2X_KhhWnEiuwJGcSlpR-5ef2HRqfaH_NB1IcqNJ4vNb1cLwIZqky5fCAGw_W4fEiHUnp8ge4_PwWE6n4VnhpaBVzSQTSkhfKK1yGN8oSNYskPPkvhtu3U_iFDeeKw00xfMkhiRtfo3xoQXQaKCZf1gcQIXga3ukOvVNTCKbMgfQQwJ2MJVH',
    liveDemoUrl: '/demo/sodamjae',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', 'Project Detail Modal', 'Hanok Quote Wizard'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      '도편수 직영 68+ 완공 한옥 아카이브 & 상세 모달',
      '전통 결구(사개맞춤) 공법 & 현대 패시브 단열 하이브리드 설계 인터랙션',
      '실시간 한옥 건축 상담 및 1:1 맞춤 견적 가이드 접수 위저드',
      '단독 살림집·별서 세컨하우스·도심형 한옥 카테고리별 동적 필터링',
    ],
  },
  {
    id: 'general-construction-corp',
    title: '종합건설사 디지털 포트폴리오 & 수주 브로슈어',
    client: '도급 순위 중견 종합건설기업',
    category: 'architecture',
    categoryName: '건축 · 종합건설',
    summary: '관급 토목부터 대형 상업 복합빌딩까지 50여 건의 시공 실적 디지털 아카이브',
    description: '관급 공사 입찰 및 민간 개발 수주 심사에 최적화된 종합건설사의 공식 포트폴리오 웹사이트입니다. 공사 규모, 완공일, 발주처, 특허 공법별 실시간 필터링과 원클릭 실적증명서 다운로드를 지원합니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'Search & Filter Engine'],
    period: '3주',
    year: '2025',
    badge: '수주 특화 웹',
    highlights: [
      '50여 건 대형 시공 실적 카테고리별 다이내믹 필터링',
      '발주처 제출용 고해상도 PDF 브로슈어 생성',
      '주요 특허 공법 및 안전보건경영시스템(ISO) 인증관',
    ],
  },
  {
    id: 'modern-timber-residence',
    title: '모던 중목구조 주택 & 전원 단지 시공 브랜드',
    client: '프리미엄 목조주택 전문 시공사',
    category: 'architecture',
    categoryName: '건축 · 주택시공',
    summary: '내진 1등급 친환경 독일식 목조주택 공법 소개 및 3D 모델하우스 투어',
    description: '일본 중목 가공 프리컷(Pre-cut) 정밀 공법과 독일식 패시브 창호 기술을 적용한 단독주택 브랜드 사이트로, 단지별 분양 안내 및 3D 모델하우스 가상 뷰어를 탑재했습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Three.js / WebGL', 'Tailwind CSS', 'TypeScript'],
    period: '3주',
    year: '2025',
    badge: '3D 가상 투어',
    highlights: [
      'WebGL 기반 3D 주택 단면 구조 분해도',
      '단지별 잔여 필지 실시간 분양 현황판',
      '건축주 맞춤형 시공비 견적 시뮬레이터',
    ],
  },
  {
    id: 'logistics-plant-engineering',
    title: '대형 저온물류센터 & 플랜트 엔지니어링 실적 웹',
    client: '산업 플랜트 엔지니어링 그룹',
    category: 'architecture',
    categoryName: '건축 · 물류/플랜트',
    summary: '연면적 3만 평 규모 자동화 물류창고 및 냉동 플랜트 시공 테크 웹사이트',
    description: '초저온 단열 공법과 바닥 평탄도(Superflat Floor) 시공 기술력을 해외 화주 및 자산운용사에 어필할 수 있는 영문/국문 듀얼 테크니컬 쇼케이스입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'i18n Multi-language', 'Tailwind CSS', 'TypeScript'],
    period: '3주',
    year: '2025',
    badge: '플랜트 테크',
    highlights: [
      '국문/영문 다국어 원클릭 스위칭',
      '바닥 평탄도(F-number) 계측 데이터 시각화',
      '친환경 물류센터 BREEAM 인증 실적 소개',
    ],
  },
  {
    id: 'atelier-arch-firm',
    title: '하이엔드 단독주택 건축사사무소 아카이브',
    client: '하이엔드 단독주택 전문 건축사사무소',
    category: 'architecture',
    categoryName: '건축 · 설계사무소',
    summary: '자연 경관과의 대화를 담은 15개 명작 단독주택 건축 아카이브',
    description: '건축 도면의 엄격한 비례감과 사진작가의 흑백/컬러 화보를 조화롭게 배치한 건축사사무소 공식 웹사이트입니다. 설계 의도와 모형 제작 과정이 수록되어 있습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'Minimalist Gallery'],
    period: '2주',
    year: '2024',
    badge: '설계 아카이브',
    highlights: [
      '건축 평면도-입면도 인터랙티브 오버레이',
      '건축 모형 360 회전 인터랙티브 뷰어',
      '출판 서적 및 학술 논문 아카이브',
    ],
  },
  {
    id: 'civil-bridge-engineering',
    title: '교량·터널 특수 토목 엔지니어링 웹사이트',
    client: '특수 교량 설계 전문 엔지니어링사',
    category: 'architecture',
    categoryName: '건축 · 토목기술',
    summary: '사장교·현수교 케이블 진동 제어 및 내진 보강 특허 기술 소개',
    description: '국내외 100여 개 교량 안전진단과 내진 보강 실적을 보유한 토목 엔지니어링 기업의 기술 신뢰도를 극대화한 인터랙티브 웹사이트입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript'],
    period: '3주',
    year: '2024',
    badge: '특수 교량 공법',
    highlights: [
      '지진파 시뮬레이션 인터랙티브 애니메이션',
      '전국 교량 시공 실적 지도(Map) 연동',
      '특허 기술 시방서 열람 시스템',
    ],
  },
  {
    id: 'urban-regeneration-reno',
    title: '성수·문래 폐공장 도시재생 리노베이션 아카이브',
    client: '도시재생 전문 건축 그룹',
    category: 'architecture',
    categoryName: '건축 · 리모델링',
    summary: '붉은 벽돌과 철골 트러스를 보존하며 신축 이상의 가치를 만든 재생 건축',
    description: '기존 건축물의 역사적 유산을 보존하면서 현대적 내진/단열 보강을 완료한 도시재생 프로젝트를 스토리텔링 방식으로 풀어낸 디지털 포트폴리오입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript'],
    period: '2주',
    year: '2024',
    badge: '도시재생 실적',
    highlights: [
      '1970년대 원형 공장과 현재 재생 공간의 비교 기록',
      '건축물 안전진단 등급 상향 과정 투명 공개',
      '관할 지자체 도시재생 대상 수상 소개',
    ],
  },

  // ─── 04. SAAS (B2B SaaS) ─────────────────────────────────
  {
    id: 'tdocs-legal-saas',
    title: 'T-DOCS (티독스) - 카카오 10초 전자서명 SaaS',
    client: '주식회사 태문 직영 SaaS',
    category: 'saas',
    categoryName: 'SaaS · 전자서명',
    summary: '300여 종 산업 서식 지면 에디터와 카톡 모바일 10초 전자서명 플랫폼',
    description: '건축, 인테리어, 부동산, 일반 기업 실무에 필수적인 300여 종의 전문 서식을 웹 에디터로 실시간 작성하고, 카카오 알림톡으로 전송하여 1분 만에 전자서명을 체결하는 올인원 스마트 도큐먼트 플랫폼입니다. 전자서명법 제3조 준수 감사추적증명서가 발급됩니다.',
    thumbnailUrl: '/images/mockup_tdocs.jpg',
    externalUrl: 'https://tdocs.kr',
    techStack: ['Next.js', 'React', 'Supabase RLS', 'PortOne V2', 'SOLAPI Alimtalk', 'Vector PDF'],
    period: '4주',
    year: '2026',
    badge: '직영 운영 서비스',
    highlights: [
      '300여 종 전문 서식 반응형 지면 프리뷰 에디터',
      '카카오톡 원클릭 전자서명 및 감사추적 증명서 발급',
      'PDF 벡터 엔진 기반 타임스탬프 위변조 방지',
      '정기 구독 빌링 및 포인트 복합 결제 시스템',
    ],
  },
  {
    id: 'taemun-bridge-platform',
    title: '태문브릿지 - 건축·설비 B2B 매칭 & 안심정산',
    client: '주식회사 태문 직영 플랫폼',
    category: 'saas',
    categoryName: 'SaaS · B2B 플랫폼',
    summary: '산업 엔지니어링 매칭 및 에스크로 기반 단계별 기성 검수 정산 시스템',
    description: '건축, 인테리어, 기계설비 분야의 의뢰인과 검증된 전문 시공팀을 연결하는 B2B 플랫폼입니다. 7단계 견적-계약-검수-정산 라이프사이클 관리와 PASS 본인인증, 투명한 단계별 에스크로 정산 체계를 지원합니다.',
    thumbnailUrl: '/images/mockup_taemun_bridge.jpg',
    externalUrl: 'https://taemun.co.kr',
    techStack: ['Next.js', 'Supabase RLS', 'PortOne PASS', 'Tailwind CSS', 'Admin CMS'],
    period: '6주',
    year: '2025',
    badge: '직영 운영 서비스',
    highlights: [
      '7단계 견적-계약-검수-정산 라이프사이클 엔진',
      'PASS 본인인증 및 안전한 기성 정산 모듈',
      '전문가 프로필 및 실적 포트폴리오 관리 시스템',
      '견적 상태 변경 카카오 알림톡 자동 통보',
    ],
  },
  {
    id: 'smart-quote-crm',
    title: '산업 맞춤형 자동 견적 산출기 & 고객 CRM',
    client: '인테리어 자재 유통 B2B 기업',
    category: 'saas',
    categoryName: 'SaaS · 견적자동화',
    summary: '평형·자재별 실시간 단가 자동 계산 및 계약서 원클릭 생성 CRM',
    description: '고객이 웹에서 면적, 자재 스펙, 시공 항목을 선택하면 3초 만에 상세 내역서와 견적서 PDF가 생성되고 영업 담당자에게 리드가 자동 배정되는 B2B 세일즈 자동화 솔루션입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Supabase', 'PDF Generator'],
    period: '3주',
    year: '2025',
    badge: '세일즈 자동화',
    highlights: [
      '면적·공종별 실시간 시공비 자동 계산 엔진',
      '견적서 원클릭 PDF 출력 및 고객사 이메일 발송',
      '영업 파이프라인 단계별 칸반 보드 CRM',
    ],
  },
  {
    id: 'field-work-daily-log',
    title: '건설 현장 모바일 작업일보 & 자재 수불 SaaS',
    client: '전문건설업체 20개사 연합',
    category: 'saas',
    categoryName: 'SaaS · 현장관리',
    summary: '스마트폰 사진 촬영으로 완료되는 노무 투입 공수 및 자재 입출고 관리',
    description: '현장 소장이 스마트폰으로 공종별 출력 인원과 자재 입고 사진을 등록하면 본사 공사팀 ERP로 실시간 집계되는 현장 밀착형 모바일 웹앱입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js PWA', 'Tailwind CSS', 'Supabase Storage', 'TypeScript'],
    period: '3주',
    year: '2025',
    badge: '모바일 PWA',
    highlights: [
      '오프라인 상태에서도 작성 가능한 PWA 캐싱',
      '공종별 인력 투입 공수(M/D) 자동 정산',
      '본사 ERP 연동 자재 입출고 수불부 자동 집계',
    ],
  },
  {
    id: 'labor-contract-payroll',
    title: '일용직 근로계약서 & 4대보험 급여 계산 SaaS',
    client: '인력 공급 및 파견 전문 기업',
    category: 'saas',
    categoryName: 'SaaS · 인사노무',
    summary: '모바일 전자근로계약서 체결 및 일급·주휴수당·소득세 자동 계산',
    description: '건설·물류 현장 일용직 근로자의 출역 기록을 기반으로 법정 일용근로계약서를 카카오 알림톡으로 자동 서명하고, 4대보험 공제 후 실지급액을 산출하는 노무 자동화 플랫폼입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'PostgreSQL', 'SOLAPI', 'TypeScript', 'Tailwind CSS'],
    period: '4주',
    year: '2024',
    badge: '급여 자동정산',
    highlights: [
      '전자서명법 준수 일용근로계약서 카톡 원클릭 체결',
      '국세청 일용근로소득 지급명세서 전산 매체 파일 생성',
      '신분증 진위 확인 및 통장사본 OCR 자동 인식',
    ],
  },
  {
    id: 'b2b-order-procurement',
    title: '기업 간 자재 B2B 발주 및 전자세금계산서 포털',
    client: '산업 설비 부자재 유통사',
    category: 'saas',
    categoryName: 'SaaS · 구매발주',
    summary: '거래처별 전용 단가표 적용 및 홈택스 전자세금계산서 자동 발행 연동',
    description: '300여 거래처가 각자의 할인율이 적용된 단가표로 웹 발주를 진행하고, 출고 완료 시 국세청 홈택스 전자세금계산서가 자동 역발행되는 올인원 B2B 구매 플랫폼입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Supabase', 'Popbill API', 'TypeScript', 'Tailwind CSS'],
    period: '4주',
    year: '2024',
    badge: '발주-세금계산서',
    highlights: [
      '거래처별 맞춤형 단가표 및 여신 한도 관리',
      '팝빌 API 연동 국세청 전자세금계산서 1초 발행',
      '품목별 재고 부족 시 공급사 자동 발주 알림',
    ],
  },

  // ─── 05. 쇼핑몰 커머스 (Commerce) ─────────────────────────────────
  {
    id: 'atelier-noir-select',
    title: '아틀리에 누아르 (ATELIER NOIR) K-패션 & 디자이너 셀렉트샵',
    client: '하이엔드 디자이너 브랜드 & 스트릿웨어 온라인 셀렉트숍',
    category: 'commerce',
    categoryName: '커머스 · 패션/셀렉트샵',
    summary: '무신사·29CM 스타일의 4단계 딥 카테고리 HUD, 인터랙티브 룩북 쇼퍼블 펄스 핀, 체형별 실측 치수 조견표 및 실시간 랭킹 시스템',
    description: '대한민국 대표 디자이너 패션 셀렉트숍의 핵심 UX를 집약한 플래그십 이커머스 라이브 데모입니다. 4단계(대·중·소·세) 카테고리 트리와 컬러/핏/소재 정밀 필터, 2026 S/S 런웨이 쇼퍼블 펄스 핀, 어깨/가슴/소매/총장 실측 cm 매트릭스, 장바구니/위시리스트 드로어 및 성수·한남 스트릿 아카이브를 탑재했습니다.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD-dtknuyBxqWqoDO2WD5FfQSpKwSH3JcoXFfAlz77N0EPzdYvqlW9kDhoOKa79Al96jiKqTjgI4N58kLtTAP61nClqAAMkeX-a6z-tbbA2rJnNn5Y98J2GL_fTDkKk82bl-dSi1AE6bZKmpT31jeq7XBZvnJh-vLV9dJxEHrdB-FHp-8EpJxL6U2TIYTkMIBY4HjXhsOXPf54kxhewQNxTWvwT6Xbv48nGYQJqoroRGVXeUCmrNLW3',
    liveDemoUrl: '/demo/atelier-noir',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', '4-Tier Deep Category HUD', 'Shoppable Pulse Pins', 'Fit Measurement Matrix', 'Real-time Live Ranking Engine'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      '대·중·소·세분류 4단계 카테고리 트리 및 컬러·핏·소재 다면 필터링 HUD',
      '2026 S/S 런웨이 인터랙티브 룩북 쇼퍼블 펄스 핀 & 3-Piece 코디 세트 원클릭 담기',
      '실시간 1~12위 랭킹 탭, 타임세일 카운트다운, 전신·디테일 접사 줌 갤러리',
      '어깨·가슴·소매·총장 cm 실측 조견표, 모델 스펙 가이드, 위시리스트 & 장바구니 드로어',
    ],
  },
  {
    id: 'verde-gourmet-grocery',
    title: '베르데 고메 (VERDE GOURMET) 프리미엄 신선식품 & 새벽배송',
    client: '산지 직송 오가닉 식료품 & 미식가 큐레이션 D2C 그로서리',
    category: 'commerce',
    categoryName: '커머스 · 신선식품/새벽배송',
    summary: '마켓컬리 스타일의 산지 직송 스토리, 셰프의 레시피 연계 재료 일괄 담기, 영하 18℃ 풀콜드체인 실시간 안심 텔레메트리 및 새벽배송 타이머',
    description: '대한민국 프리미엄 그로서리 커머스의 첨단 UX를 구현한 플래그십 이커머스 라이브 데모입니다. 횡성 1++ No.9 숙성 한우부터 제주 새벽 직송 유기농 채소까지, 보관온도대별(냉장/냉동/상온) 실시간 필터와 100g당 투명 단가 공시, 셰프 레시피 재료 원클릭 일괄 담기 및 도심 허브 풀콜드체인 관제 로그를 제공합니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '/demo/verde-gourmet',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', 'Full Cold-Chain Telemetry', 'Chef Recipe Batch Cart', 'Dawn Delivery Countdown', 'Temperature Zone Matrix'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      '오늘 밤 11시 주문 마감 실시간 샛별배송 카운트다운 타이머',
      '냉장(0~2℃) · 냉동(-18℃) · 상온 보관 형태별 스마트 필터링 및 100g당 단가 표시',
      '전문 셰프의 지중해식 한우 타르타르 레시피 식재료 선택 후 원클릭 일괄 장바구니 담기',
      '산지 출하부터 문 앞 배송까지 4단계 실시간 풀콜드체인 온도 모니터링 텔레메트리',
    ],
  },
  {
    id: 'luminous-lab-derma',
    title: '루미너스 랩 (LUMINOUS LAB) K-뷰티 & 클린 더마 코스메틱',
    client: '글로벌 K-뷰티 & 클린 더마 코스메틱 D2C 플래그십',
    category: 'commerce',
    categoryName: '커머스 · 뷰티/코스메틱',
    summary: '올리브영·화해 스타일의 피부타입 및 피부고민별 4단계 딥 필터 HUD, 전성분 EWG 그린 안전 등급 검사기, 실시간 뷰티 어워즈 랭킹 차트 및 임상 시험 리포트',
    description: '글로벌 K-뷰티 트렌드를 선도하는 프리미엄 더마 코스메틱 플래그십 이커머스 라이브 데모입니다. 시카 엑소좀 수분 앰플부터 히알루론산 장벽 크림까지, EWG 100% 그린 등급 성분 사전과 텍스처 발림성 비교, 피부타입(건성/수부지/지성/민감성) 및 피부고민별 4단계 맞춤 필터링, 실시간 어워즈 랭킹 및 1:1 피부과 전문의 상담 위저드를 탑재했습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '/demo/luminous-lab',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', 'EWG Safety Grade Inspector', 'Skin Concern 4-Tier HUD', 'Clinical Trial Telemetry', 'Live Beauty Awards Engine'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      '피부타입(수부지·건성·지성) 및 피부고민(장벽·진정·모공) 맞춤 4단계 다면 필터링 HUD',
      '20가지 유해의심성분 ZERO 및 100% EWG 그린 등급 포뮬러 실시간 성분 검사기',
      '올리브영 스타일 실시간 1~8위 랭킹 차트 및 앰플+장벽크림 시너지 번들 특가 담기',
      '4주 피부과 임상 시험 리포트 모달, 1:1 피부 진단 퀴즈 및 오늘드림 당일 배송 조회',
    ],
  },
  {
    id: 'technova-gear-hardware',
    title: '테크노바 기어 (TECHNOVA GEAR) 디지털 가전 & 하이테크 기어',
    client: '하이엔드 게이밍 랩탑 & 정밀 테크 하드웨어 D2C 플래그십',
    category: 'commerce',
    categoryName: '커머스 · 가전/테크기어',
    summary: '다나와·쿠팡IT 스타일의 파라메트릭 정밀 하드웨어 스펙 비교 매트릭스, 3D 쿨링 챔버 분해도 뷰어, 섀시 I/O 포트 텔레메트리 맵 및 실시간 벤치마크 엔진',
    description: '대한민국 하이테크 하드웨어 커머스의 정점을 보여주는 플래그십 이커머스 라이브 데모입니다. RTX 4080/4090 랩탑부터 마그네틱 홀센서 키보드까지, 파라메트릭 스펙 필터 HUD, 2~4개 모델 동시 스펙 대조 매트릭스, 베이퍼 챔버 3D CAD 분해도 모달 및 6면 I/O 포트 매크로 뷰어를 제공합니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '/demo/technova-gear',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', 'Parametric Spec Matrix', '3D Vapor Chamber CAD Inspector', 'Chassis I/O Port Telemetry', 'Side-by-Side Model Comparator'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      'RTX 4080/4090 · Core Ultra 9 · 240Hz OLED · 32GB RAM 파라메트릭 스펙 필터 HUD',
      '다나와 스타일 4개 모델 동시 스펙 대조 비교 매트릭스 및 실시간 텔레메트리 연동',
      '베이퍼 챔버 듀얼 팬 쿨링 아키텍처 3D 분해도 모달 및 터보 파워모드 실시간 시뮬레이터',
      '썬더볼트4 · HDMI 2.1 · 2.5G LAN 섀시 I/O 포트 전후좌우 매크로 인터랙티브 맵',
    ],
  },
  {
    id: 'maison-d-antique',
    title: "메종 당티크 (Maison d'Antique) 오리지널 유러피안 앤틱 살롱",
    client: '1884 파리·런던 직영 앤틱 아카이브 살롱',
    category: 'commerce',
    categoryName: '커머스 · 하이엔드/D2C',
    summary: '18~19세기 프랑스 루이 15세부터 조지안 시대 오리지널 앤틱 가구 & 공예품 큐레이션 D2C 살롱',
    description: '파리, 런던, 피렌체 직영 옥션 및 귀족 가문 전승 오리지널 앤틱을 선별 소개하는 최고급 앤틱 큐레이션 살롱 웹사이트입니다. 카테고리별 아카이브 검색, 뮤지엄 그레이드 작품 상세 도록 모달, 소장 희망 서류함(CartFolio), 관심작 보관함(Wishlist) 및 한남동 살롱 프라이빗 뷰잉 예약 시스템을 탑재했습니다.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDG3U71UG2sag7nQaN1upmn1zWrQnzXY02ruI2hGXrq5TDNvU83YgjmO_yG9EDVJ7xhY2EkfmHOVVmonJNe_5iwO--N2OsB04DWSzfOthE8_wQz290_uVqWmBJu_rUTdObJKyPQtGO2qxMdySwi7bP0m0S6vfDbP8goS6g4nrqNwum0CCuMMRi4J9hWqNyNcUOn3DrGhT5828Av6L2H7ztIwtUaA2RS9Aq9EcgUgNhJkDse-o3NLHj5',
    liveDemoUrl: '/demo/maison',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', 'Curator Dossier Modal', 'Acquisition Folio'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      '18~19세기 프랑스 루이 15세 오리지널 코모드 등 희귀작 아카이브 도록',
      '소장 희망 서류함(CartFolio) 및 관심작 위시리스트 드로어 인터랙션',
      '전 품목 실시간 다각도 검색 모달 및 4대 카테고리 필터링',
      '한남동 살롱 1:1 프라이빗 뷰잉 및 고가구 복원 컨설팅 예약 위저드',
    ],
  },

  // ─── 06. 기업 랜딩 (Corporate) ─────────────────────────────────
  {
    id: 'nexus-robotics-fleet',
    title: '넥서스 로보틱스 (NEXUS ROBOTICS) 클린룸 자율주행 AMR 엔터프라이즈',
    client: '가상 브랜드 샘플 — 클린룸 자율주행 로보틱스 설정',
    category: 'corporate',
    categoryName: '기업랜딩 · AI/로보틱스',
    summary: 'ISO Class 1 클린룸 인증, 초당 100회 라이다·비전 SLAM 및 0.5mm 초정밀 도킹 자율 군집 로봇',
    description: '반도체 웨이퍼 카세트 및 2차전지 전극 롤 무인 이송을 위한 하이엔드 로보틱스 플래그십 사이트입니다. 3대 로봇 라인업(AMR-500/1500/3000) 360 스펙 브로슈어, 실시간 148노드 NEXUS-OS 디지털 트윈 팹 관제 뷰어, 면적 및 교대 인력 기반 대화형 ROI 계산기를 탑재했습니다.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCP0LMDqPo3TTPJeMeKFrsp9v6KD1_GZ7i-IEqGGvYOfAPKyEP3BduxA8tBVL4SpEEGcBuFuzsTugFEAYD9v1z-bkuded04fQo_0L1gl2jKhAapE3xJOZMOizin9QytSuIbnPmVt-xOBXQ6U8gH-q21B5gsTegSQ9z1KF9dTNufQwkMLm_RNBNtVQqlw4DhSIWETyLWP52RmrtauTdiRpqmYxhn5UqIKI2HMsPsfw7LOZxFP5ONPXKf',
    liveDemoUrl: '/demo/nexus-robotics',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', 'Digital Twin HUD', 'Interactive ROI Matrix'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      '3D LiDAR·비전 SLAM 다중 센서 융합 & 0.5mm 정밀 도킹',
      '148노드 무교착(Zero-Deadlock) NEXUS-OS 디지털 트윈 뷰어',
      '공장 면적/교대 인력별 연간 절감액 & 투자 회수기간 실시간 계산기',
      'ISO 14644-1 Class 1 클린룸 규격 인증 및 현장 실사 신청 위저드',
    ],
  },
  {
    id: 'h2-next-energy',
    title: '하이드로젠 넥스트 (H2 NEXT) 차세대 신재생에너지 & 그린수소 엔터프라이즈',
    client: '가상 브랜드 샘플 — 신재생에너지·액화수소 기업 설정',
    category: 'corporate',
    categoryName: '기업랜딩 · 신재생에너지/수소',
    summary: '1.8GW 해상풍력 연계 PEM 수전해 플랜트, -253℃ 극저온 액화수소 SCM 및 RE100 PPA 금융 플랫폼',
    description: '노르딕 클린테크 감성의 대형 신재생에너지 엔터프라이즈 플래그십 사이트입니다. 신안·울산·포항 4대 발전 거점 실시간 SCADA 텔레메트리 연동 맵, 기업용 연간 전력 사용량 기반 K-ETS 탄소 배출권 및 PPA 금융 절감 계산기, 국제 인증기관(예시) 그린수소 인증관을 완비했습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '/demo/h2-next',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', 'SCADA Hub Map', 'Carbon PPA Calculator'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      'GW급 해상풍력 연계 고효율 PEM 수전해 플랜트 쇼케이스',
      '신안·울산·포항 4대 발전 거점 실시간 SCADA 텔레메트리 맵',
      '기업용 연간 전력 사용량별 K-ETS 탄소 감축액 & PPA 계산기',
      '그린수소 인증 표기(예시) 및 지속가능경영보고서 지면',
    ],
  },
  {
    id: 'celebris-biopharma-pipeline',
    title: '셀레브리스 바이오파마 (CELEBRIS BIOPHARMA) 표적단백질분해 & ADC 혁신신약',
    client: '가상 브랜드 샘플 — 바이오텍 기업 설정',
    category: 'corporate',
    categoryName: '기업랜딩 · 바이오/신약개발',
    summary: '자체 AI 발굴 엔진 PROTEA-AI, 표적 단백질 분해(TPD/PROTAC) 및 차세대 ADC 글로벌 파이프라인 매트릭스',
    description: '순백의 딥사이언스 무균 연구실 감성으로 설계된 글로벌 바이오텍 플래그십 사이트입니다. 4대 항암 파이프라인(CB-101/204/308/401) 실시간 임상 단계 트래커, 3D 분자 작용기전(MoA) 영상 모달, 송도 12,000평 cGMP 생산 시설 가상 투어, 글로벌 제약사 BD 전용 기술수출(L/O) 및 CDA/NDA 체결 위저드를 완비했습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '/demo/celebris-biopharma',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', 'Pipeline Matrix', 'MoA 3D Viewer'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      'CB-101 비소세포폐암 희귀의약품 지정 표기(예시) & 임상 2상 트래커',
      '자체 PROTEA-AI 신약 발굴 엔진 & 3D 분자 작용기전(MoA) 뷰어',
      '송도 12,000평 2,000L 싱글유즈 cGMP 바이오리액터 인프라',
      '글로벌 빅파마 BD 기술수출(L/O) 파트너링 미팅 & VDR 신청 위저드',
    ],
  },
  {
    id: 'nano-advanced-semiconductor',
    title: '나노어드밴스드 (NANO ADVANCED) 2.5D/3D 반도체 첨단 패키징 & 글래스 기판',
    client: '가상 브랜드 샘플 — 첨단 반도체 패키징 기업 설정',
    category: 'corporate',
    categoryName: '기업랜딩 · 반도체/첨단패키징',
    summary: '초거대 AI 칩셋을 위한 2.5D/3D 첨단 이종 반도체 패키징, 초평탄 글래스 코어 기판, 실시간 열/휨 시뮬레이터',
    description: '스위스·노르딕 감성의 하이엔드 테크 클린룸 디자인으로 설계된 반도체 첨단 패키징 플래그십 사이트입니다. L1 로직 다이부터 L4 글래스 코어 기판까지 4단계 마이크로 아키텍처 인터랙티브 익스플로러, HBM 스택별 실시간 열/휨(Warpage) 시뮬레이션 리포트 생성기, 99.85% 양산 수율 파운드리 5단계 비파괴 검사 공정 안내를 제공합니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '/demo/nano-advanced',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', 'Micro-Architecture Explorer', 'Thermal Simulator'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      'L1 Top Logic~L4 Glass Substrate 4단계 마이크로 인터커넥트 익스플로러',
      'HBM4 스택 수 및 TDP에 따른 실시간 발열·휨 계측 및 엔지니어링 리포트 생성',
      '글로벌 파운드리 5단계 비파괴 나노 단층 검사 & 99.85% 양산 수율 체계',
      '팹리스·파운드리 전용 웨이퍼 테스트 샘플 및 기술 실무 미팅 접수 위저드',
    ],
  },
  {
    id: 'stella-orbital-systems',
    title: '스텔라 궤도 데이터 (STELLA ORBITAL) 초소형 위성 군집 & 지구관측 AI',
    client: '가상 브랜드 샘플 — 위성 데이터 기업 설정',
    category: 'corporate',
    categoryName: '기업랜딩 · 우주항공/스페이스테크',
    summary: '태양동기궤도 500km 초소형 위성 군집, 0.3m 초고해상도 광학 & X-Band SAR 레이더, 실시간 텔레메트리 다운링크',
    description: '순백 스페이스테크 클린룸 감성으로 설계된 지구관측 위성 데이터 플랫폼 플래그십 사이트입니다. 광학(EO)·합성개구레이더(SAR)·초분광 3대 센서 인터랙티브 해상도 비교 뷰어, 국방/해양/인프라 분석 솔루션 매트릭스, 전 세계 14개 지상국 다운링크 텔레메트리 HUD, 촬영 위임 의뢰(Tasking) 위저드를 완비했습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '/demo/stella-orbital',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', 'Multi-Sensor Radar', 'Live Orbit HUD'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      '0.3m 서브미터 컬러 광학 & X-Band SAR 3대 센서 인터랙티브 비교 뷰어',
      '48기 LEO 저궤도 위성 군집 실시간 다운링크(10Gbps OISL) 텔레메트리 HUD',
      '국방 해양 감시, 송유관 인프라 변위, 곡물 수확량 글로벌 분석 솔루션',
      '관심 영역(AOI) 지정, 전천후 센서 선택 및 Cloud GeoTIFF 촬영 의뢰 위저드',
    ],
  },
  {
    id: 'apex-partners-fund',
    title: '아펙스 파트너스 (APEX PARTNERS) 글로벌 사모펀드(PE) & VC 대체투자',
    client: '글로벌 기관투자자(LP) 및 AUM 4.2조 원 대체자산운용사',
    category: 'corporate',
    categoryName: '기업랜딩 · 사모펀드/VC 대체투자',
    summary: 'AUM 4.2조 원, 10년 누적 Net IRR 24.8%, 플래그십 바이아웃·딥테크 그로쓰 및 기관 전용 VDR 게이트',
    description: '월스트리트 및 스위스 프라이빗 뱅킹 감성의 최고급 사모펀드·대체자산운용사 플래그십 사이트입니다. 4대 투자 전략(바이아웃·딥테크·인프라·크레딧) 매트릭스, 48개 포트폴리오 기업 및 회수(Exit) 실적 모달, 약정액·투자기간 기반 실시간 Net IRR 및 DPI 분배금 계산기, 연기금/국부펀드 전용 에어갭 VDR 신청 시스템을 완비했습니다.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCe68hJkQbw3iNmUtaebjkqXeO060iE8Wo98SB-sxwQT03Q_rb8tTYuhBDmAsUkFL2feqfv13g7HliVuFDY_kR5rmZj6nJ34Mxf-2zs5vNUXQBwICKmSoR0OP8jzTrhmEvqg-XVSPx5nS0RZ2TK0_04ie3Cu9w0iA_53haUrDJI6Z0LPhu3EZWOn-IuGLIXBImWSV-CFBvl-I8rbDE2HWoWORpAugUSA6m6ewU52zVg5ekoWQrbHEIh',
    liveDemoUrl: '/demo/apex-partners',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', 'Actuarial IRR Simulator', 'Air-Gapped VDR Gate'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      'AUM 4.2조 원 ($3.2B) & 10년 누적 Net IRR 24.8% 실시간 금융 텔레메트리',
      '플래그십 바이아웃, 딥테크 그로쓰, 인프라, 사모대출 4대 전략 인터랙티브 필러',
      '출자 약정액(100억~1,000억) 및 목표 배수 조절 실시간 Net IRR/DPI 분배 시뮬레이터',
      '기관투자자(LP) 전용 가상 데이터룸(VDR) 신청 및 NDA 전자 서약 워크플로우',
    ],
  },
  {
    id: 'atlas-resorts-collection',
    title: '아틀라스 리조트 컬렉션 (ATLAS RESORTS) 럭셔리 부티크 & 프라이빗 빌라',
    client: '글로벌 하이엔드 호스피탈리티 & 프라이빗 에스테이트 엔터프라이즈',
    category: 'corporate',
    categoryName: '기업랜딩 · 럭셔리호텔/호스피탈리티',
    summary: '남해 60m 절벽 인피니티 풀빌라, 제주 원시 곶자왈 프레지덴셜 에스테이트, 발리 우붓 생츄어리',
    description: '아만(Aman) 및 슈발블랑(Cheval Blanc) 감성의 최고급 부티크 리조트·프라이빗 빌라 플래그십 사이트입니다. 3대 건축 스위트 익스플로러, 여행지·숙박일수·비포크 옵션 실시간 견적 계산기, 미쉐린 파인다이닝 & 프라이빗 웰니스 스파 쇼케이스, VIP 전용기·요트 컨시어지 직통 접수 시스템을 완비했습니다.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCozZMbR8Jj_DCUr1G4KdKVhg1Km_XGNvRaUqLuPu1pyq5_u_xxpiDZlJYY1PGXfrGXYtT0AKi7u15kfplSs9hcWE313IyFJ-XxojYYraGXG7RFMWyd3w5qtNjgFbAaP2ZQJBzK82r4iXoJoxpEofko7qgLzgGqIzZLTOEsoED8JYjzwIxmp9G_xzo6fLvLK32BlvV441TGya_7B7TDAftUK5JzVyU7hB6PTjj0m6l20UREWjnFy99X',
    liveDemoUrl: '/demo/atlas-resort',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', '360 Villa Suite Explorer', 'Dynamic Season Calculator'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      '남해 절벽·제주 곶자왈·발리 우붓 3대 건축 스위트 파빌리온 익스플로러',
      '목적지 배수·박수·비포크 애드온(요트/소믈리에 디너) 실시간 숙박비 계산기',
      '전 객실 18m 온수 인피니티 풀, 전담 버틀러 동선, B&O 하이파이 사운드 완비',
      'VIP 에어포트 픽업, 헬리콥터 트랜스퍼 및 프라이빗 차터 컨시어지 게이트',
    ],
  },
  {
    id: 'transocean-global-scm',
    title: '트랜스오션 글로벌 SCM (TRANSOCEAN) 스마트 항만 & AI 복합물류',
    client: '글로벌 해운선사 & 자율운항 스마트 포트 엔터프라이즈',
    category: 'corporate',
    categoryName: '기업랜딩 · 스마트항만/해운물류',
    summary: '부산신항-로테르담 실시간 AIS 선박 추적, -18℃ 초저온 콜드체인 IoT 관제 및 복합운임 시뮬레이터',
    description: '머스크(Maersk) 스타일의 글로벌 스마트 항만 & AI 복합물류 플래그십 사이트입니다. B/L 선하증권 실시간 GPS 선박 및 컨테이너 텔레메트리 HUD, 해상·항공·철도 운송모드별 실시간 운임 및 Scope-3 탄소 감축 계산기, 부산·로테르담·싱가포르·LA 4대 거점 항만 혼잡도 레이더 모달, 글로벌 화주 전용 RFP 운송계약 접수 데스크를 완비했습니다.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBuE0Y8RrN9OOxGpEeoWuEgELTCS4QdPMmlbE5NvfykOlmb00zrPz1BdUv7K4-C487l86IZMqzgy_TfyE6rNh6r0aFzVmEnAoHeK1DBYaDqY8lYwR46NBhEpySKdmu-hLtfe9JtOtvJvJnKOXLHVAJFUeF0SsHEEDTlWk7EGgLbFF2GZOusQgPrdtuCBOFWNJABA6m10QHPDGU9yIJxZ-qyOyqWVLa4FCLVdvkCFmNjmtR5AbHDLKd5',
    liveDemoUrl: '/demo/transocean-scm',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', 'AIS Vessel HUD', 'Port Radar Modal', 'Multimodal Carbon Matrix'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      'B/L 선하증권 실시간 항로, -18.2℃ 냉동 리퍼 온습도 & 충격 센서 텔레메트리 HUD',
      '해상·항공·급행철도 리드타임 & Scope-3 CO2 탄소배출량 비교 시뮬레이터',
      '부산신항·로테르담·LA 등 글로벌 4대 항만 실시간 혼잡도 및 선석 레이더',
      '5G 자율주행 스트래들 캐리어, 그린 메탄올 에코 선대 4대 자동화 필러',
    ],
  },
  {
    id: 'voltron-advanced-ev',
    title: '볼트론 EV 전장 솔루션 (VOLTRON) 800V SiC 전력반도체 & 메가와트 충전',
    client: '글로벌 완성차 Tier-1 전기차 파워트레인 & 전력반도체 엔터프라이즈',
    category: 'corporate',
    categoryName: '기업랜딩 · 전기차/전력반도체',
    summary: '차세대 800V SiC 인버터, 15분 메가와트 초급속 충전 & 열관리 시뮬레이터 및 ASIL-D 인증관',
    description: '글로벌 완성차 Tier-1 전장 엔지니어링 기업을 위한 하이퍼 테크 플래그십 사이트입니다. 배터리 용량 및 주변온도별 실시간 800V 충전 속도·열방출 시뮬레이터, 3세대 SiC 전력 인버터 분해 마이크로 아키텍처 뷰어, 실시간 120kHz 스위칭 오실로스코프 파형 계측기, ISO 26262 ASIL-D 전장 안전 인증 및 기술 백서 다운로드 게이트를 완비했습니다.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDuH9dhKEGOXl9MUS1-15lZbD4svmbG6pkN0tXJsQB5cLosabyyekdX6Mrw74JD4U4zqRKJZw87--7ry_hmFPDEHiRgjjrvVDAIa4n-F1YKb6tks3OnGrtmhf4MgZQQk8hEWveISYYxEYqYfrxm10t4ArOyp5P4KhqgoePRDYOqdlOduTh1aZLq5j17bBGbAvW4qRlJPSWMjNNEYfS2kkPXEPN4204kOB9bnpudWwHeE9rpeOy_O34E',
    liveDemoUrl: '/demo/voltron-ev',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', 'Charging Simulator', 'Architecture Explorer', 'ASIL-D Dossier'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      '800V 배터리(75~120kWh) 및 온도(-20~45℃) 조절 초급속 충전 곡선 시뮬레이터',
      'Gen-3 SiC 인버터, 고전압 정션박스 3D 분해 마이크로 아키텍처 뷰어',
      'ISO 26262 ASIL-D, AEC-Q101 전장 인증 및 기밀 엔지니어링 백서 다운로드 게이트',
      '글로벌 OEM 양산 사양 협의(RFQ) 및 총괄 아키텍트 직통 엔지니어링 상담 연동',
    ],
  },
  {
    id: 'greencube-vertical-farm',
    title: '그린큐브 버티컬 팜 (GREENCUBE) AI 무농약 밀폐형 수직 스마트팜',
    client: '글로벌 친환경 스마트팜 & 무농약 바이오 천연물 소재 상장사',
    category: 'corporate',
    categoryName: '기업랜딩 · 스마트팜/애그리테크',
    summary: 'Class 1000 클린룸 바이오스피어, 95% 용수 절감 & 연간 수확량 계산기 및 분광 AI 매트릭스',
    description: '첨단 바이오 무균 클린룸과 청정 바이오스피어 감성의 수직 스마트팜 플래그십 사이트입니다. 재배 면적(1,000~10,000평) 및 품종별 연간 생산량(톤), 용수 95% 절감 및 탄소 감축 ROI 실시간 계산기, Blue(450nm) 엽록소 강화 vs Red(660nm) 개화 촉진 분광 LED 파장 실시간 튜너, 온습도/CO2 Class 1000 클린룸 관제 HUD, 특급호텔 및 대형마트 B2B 4시간 콜드체인 납품 계약 위저드를 완비했습니다.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAy43GOmTnr2T8zFUP4t4l8gCmRafBwVHRK3QC-R1sXlbby4-Do0Lf8ukKqlomkfQAD5cbaUdcxYvgJDQmowqHJMVj9qzPoHLLLbBPemx3bKkBiqjbiThMAlGOPuGE7IHPNxwGF89JD5MhkkOO45WCnvM7WhI8BwrXvtiP-iBBoPNCwmdSYpic-KmPyNzNcUloj7YW8lJShKrggigr_z1sGhFae9hCMuGm3YcpXobqGHbUTjvfiqIa9',
    liveDemoUrl: '/demo/greencube-agri',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', 'Spectral AI Matrix', 'Harvest Yield Calculator', 'Cold Chain HUD'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      '재배면적(1,000~10,000평) 및 품종별 연간 수확량(톤) & 용수 95% 절감 계산기',
      'Blue(450nm) 조직 치밀화 vs Red(660nm) 안토시아닌 AI 분광 매트릭스 튜너',
      'ISO Class 1000 무균 양압 클린룸 실시간 온습도·CO2 기밀 환경 텔레메트리',
      '특급호텔·항공사 케이터링 4시간 Farm-to-Table B2B 정기 계약 위저드',
    ],
  },

  // ─── 03. 병의원 · 메디컬 · 치과 (Medical & Healthcare) ───────────────────
  {
    id: 'cheongdam-arte-dental',
    title: '청담 아르떼 심미치과 & 원데이 임플란트 센터',
    client: '구강악안면외과 · 보철과 협진 임플란트 치과',
    category: 'medical',
    categoryName: '병의원 · 심미치과/임플란트',
    summary: '3D 구강 스캐너 디지털 네비게이션 가이드와 무통 마취 안심 진료 클리닉 웹사이트',
    description: '청담역 역세권에 위치한 하이엔드 심미보철·임플란트 특화 치과병원 웹사이트입니다. 구강악안면외과 및 치과보철과 전문의 2인 협진 시스템, 3D CT 및 구강 스캐너를 이용한 컴퓨터 분석 가이드 임플란트 시술 과정 소개, 1:1 맞춤형 치아 성형 비포&애프터 갤러리, 실시간 네이버 예약 및 야간진료 일정 안내를 완비했습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js 16', 'Tailwind CSS v4', 'TypeScript', 'Naver Booking API', 'Before & After 3D'],
    period: '2주',
    year: '2026',
    badge: '디지털 네비게이션',
    highlights: [
      '3D 컴퓨터 모의수술 네비게이션 임플란트 프로세스 인터랙션',
      '보철과·구강악안면외과 분과별 전문의 약력 및 학술 활동 아카이브',
      '자연치아 보존 라미네이트 & 세라믹 인레이 정밀 심미 갤러리',
      '네이버 예약 시스템 실시간 슬롯 연동 및 모바일 문진표 지원',
    ],
  },
  {
    id: 'the-noble-dermatology',
    title: '더 노블 청담 피부과의원 & 안티에이징 센터',
    client: '피부과 전문의 3인 프라이빗 리프팅 센터',
    category: 'medical',
    categoryName: '병의원 · 피부과/안티에이징',
    summary: '울쎄라·써마지 정품 인증 팁 조회 및 1인 단독 프라이빗 룸 중심 웰니스 스킨케어 웹',
    description: '피부과 전문의의 정밀 피부 정량 진단(마크뷰 영상분석)을 기반으로 한 1:1 맞춤형 리프팅·안티에이징 전문 피부과 공식 웹사이트입니다. 써마지 FLX·울쎄라 골드 스탠다드 정품 팁 인증 시리얼 넘버 실시간 확인 모듈, 비급여 수가표 투명 공개, 전 객실 1인 단독 VIP 케어룸 안내를 제공합니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS', 'Serial Verification', 'Kakao Consult'],
    period: '3주',
    year: '2026',
    badge: '정품인증 실시간조회',
    highlights: [
      '울쎄라·써마지 정품 인증 번호 즉시 검증 위젯',
      '마크뷰(Mark-Vu) 4종 광원 피부 정밀 진단 시스템 쇼케이스',
      '보건복지부 비급여 고시 규정 준수 항목별 투명 수가 공시관',
      '카카오 1초 간접 상담 및 1인 VIP 리커버리룸 동선 가이드',
    ],
  },
  {
    id: 'seoul-barun-orthopedics',
    title: '서울 바른마디 척추관절 정형외과 & 도수재활센터',
    client: '비수술 척추·관절 중점 정형외과 · 도수재활센터',
    category: 'medical',
    categoryName: '병의원 · 정형외과/재활',
    summary: '비수술 척추·관절 중점 치료, 100평 규모 도수운동재활센터 인터랙티브 로드맵',
    description: '척추 디스크, 관절 연골 손상의 비수술 체외충격파·프롤로 주사 치료부터 수술 후 1:1 도수재활까지 전 과정을 원스톱으로 관리하는 척추관절 정형외과 사이트입니다. 척추관 협착증·오십견 부위별 자가진단 인터랙티브 체크리스트와 MRI 당일 촬영·판독 원스톱 예약 시스템을 갖추고 있습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'Interactive Self-Check', 'TypeScript'],
    period: '2주',
    year: '2025',
    badge: '비수술 특화 센터',
    highlights: [
      '부위별(목·허리·어깨·무릎) 5문항 인터랙티브 자가진단 모듈',
      '최첨단 1.5T MRI 및 체외충격파(ESWT) 치료 원리 3D 가이드',
      '전문 물리치료사 1:1 맞춤 슬링·도수치료 프로그램 소개',
      '당일 검사-진단-처치 원스톱 패스트트랙 예약 프로세스',
    ],
  },
  {
    id: 'prime-vision-eye-clinic',
    title: '프라임 스마트 아이 안과 · 스마일라식 & 백내장 센터',
    client: '각막 전임의 및 노안백내장 수술 3만례 집도의 클리닉',
    category: 'medical',
    categoryName: '병의원 · 안과/시력교정',
    summary: '스마일프로 7초 레이저 시술 안내, 각막 두께·동공 크기별 시력교정술 적합도 계산기',
    description: '스마일프로, 라섹, 안내렌즈삽입술(ICL), 다초점 인공수정체 백내장 수술을 중점 집도하는 전문 안과의원 웹사이트입니다. 50여 가지 정밀 안구 종합검진 절차 소개, 내 눈에 맞는 시력교정술 인터랙티브 추천 시뮬레이터, 의료진의 수술 누적 건수 및 학회 연구 실적을 신뢰감 있게 구성했습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'Laser Simulation', 'TypeScript'],
    period: '3주',
    year: '2025',
    badge: '스마일프로 시뮬레이터',
    highlights: [
      '50가지 정밀 사전검사 가이드 및 실시간 시력교정 적합도 계산기',
      '최신 레이저 장비 7초 저자극 조사 테크 쇼케이스',
      '백내장 수술 전후 초점 거리별(원·중·근거리) 시야 시뮬레이터',
      '수술 후 주의사항 모바일 알림장 자동 전송 연동',
    ],
  },
  {
    id: 'heritage-korean-medicine-hospital',
    title: '본초 통합한방병원 & 암면역·재활 메디컬 센터',
    client: '의·한의 협진 80병상 입원집중치료 한방병원',
    category: 'medical',
    categoryName: '병의원 · 한방병원/입원실',
    summary: '의·한의 통합 진료 시스템, 1인실 중심 프리미엄 입원 집중 케어 & 원내 탕전실 투어',
    description: '양방 영상의학 진단과 한방 체질 맞춤 침·뜸·한약 처방을 통합 제공하는 80병상 규모 한방병원 공식 웹사이트입니다. 전 병실 1인실·2인실 모션베드 및 개별 테라스 360 가상 투어, GAP 인증 한약재 클린 탕전 과정 실시간 중계관, 교통사고 자동차보험 입원 절차 가이드를 지원합니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'VR 360 Inpatient Tour', 'TypeScript'],
    period: '3주',
    year: '2025',
    badge: '의·한의 통합 협진',
    highlights: [
      '80병상 전 객실 1·2인실 프리미엄 모션베드 360 파노라마 뷰어',
      '식약처 hGMP 인증 규격 한약재 탕전 과정 투명 공개 아카이브',
      '교통사고 후유증 및 암면역 재활 집중 입원 치료 프로토콜',
      '간병 통합 서비스 및 병상 잔여 현황 실시간 문의 창구',
    ],
  },
  {
    id: 'petit-facial-studio',
    title: '에스테티카 쁘띠성형 & 페이셜 컨투어링 스튜디오',
    client: '보톡스·필러·실리프팅 전문 안면윤곽 메디컬 클리닉',
    category: 'medical',
    categoryName: '병의원 · 쁘띠/성형외과',
    summary: '개인별 안면 근육 해부학 분석 기반 자연스러운 쁘띠 시술 & 전 제품 미개봉 정품 확인',
    description: '과도한 성형을 지양하고 본연의 매력을 살리는 보톡스, 필러, 콜라겐 부스터 특화 클리닉 웹사이트입니다. 시술 전 고객 눈앞에서 미개봉 정품 개봉 및 정량 주입을 확인하는 안심 프로세스, 부위별 맞춤 용량 인터랙티브 가이드, 비밀 보장 1:1 상담 예약 시스템을 탑재했습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1512290900672-1f4a9bb5f532?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'Facial Anatomy Guide'],
    period: '2주',
    year: '2024',
    badge: '정량·정품 개봉 보증',
    highlights: [
      '고객 대면 미개봉 신품 언박싱 & 정량 주입 안심 보증 캠페인',
      '얼굴 부위별(이마·턱끝·팔자) 3D 입체 윤곽 시술 효과 가이드',
      '알레르기·멍·붓기 최소화 캐뉼라 시술 노하우 소개',
      '프라이빗 100% 예약제 및 익명 카카오 비밀 상담 위젯',
    ],
  },
];
