export type GalleryCategoryId =
  | 'manufacturing'
  | 'interior'
  | 'architecture'
  | 'saas'
  | 'commerce'
  | 'corporate';

export interface GalleryCategoryMeta {
  id: GalleryCategoryId;
  number: string;
  name: string;
  engName: string;
  description: string;
  badge: string;
}

export interface GalleryProject {
  id: string;
  title: string;
  client: string;
  category: GalleryCategoryId;
  categoryName: string;
  summary: string;
  description: string;
  thumbnailUrl: string;
  liveDemoUrl?: string;
  externalUrl?: string;
  techStack: string[];
  period: string;
  year: string;
  badge?: string;
  highlights: string[];
}

export const GALLERY_CATEGORIES: GalleryCategoryMeta[] = [
  {
    id: 'manufacturing',
    number: '01',
    name: '제조 · 스마트팩토리 · 소재공정',
    engName: 'Manufacturing & Smart Factory',
    description: '수기 엑셀 장부를 실시간 통계 관리도(SPC), 수율 워터폴 분석, 4단계 로트 계보 역추적 시스템으로 디지털 전환한 엔터프라이즈 솔루션입니다.',
    badge: '정밀 제조 데이터',
  },
  {
    id: 'interior',
    number: '02',
    name: '인테리어 · 공간 디자인 · 하이엔드',
    engName: 'Interior & Spatial Design',
    description: '자연석과 원목의 질감, 절제된 세리프 타이포그래피로 공간의 격조를 극대화한 최고급 주거·상업 공간 스튜디오 웹사이트입니다.',
    badge: '하이엔드 감성',
  },
  {
    id: 'architecture',
    number: '03',
    name: '건축 · 종합건설 · 토목엔지니어링',
    engName: 'Architecture & Construction',
    description: '종합건설사, 설계사무소, 플랜트·물류센터의 수주 경쟁력을 극대화하는 시공 실적 아카이브와 공법 소개 디지털 브로슈어입니다.',
    badge: '대형 시공 수주',
  },
  {
    id: 'saas',
    number: '04',
    name: 'SaaS · 전자서약 · B2B 플랫폼',
    engName: 'B2B SaaS & Digital Platforms',
    description: '100% 법적 효력 카카오 모바일 전자서명부터 300종 법정 서식 에디터, 엔지니어링 매칭 및 단계별 안심 기성 정산 플랫폼입니다.',
    badge: '자체 직영 운영',
  },
  {
    id: 'commerce',
    number: '05',
    name: '쇼핑몰 · 이커머스 · D2C 브랜드',
    engName: 'E-Commerce & D2C Brands',
    description: '브랜드 고유의 철학을 담은 비주얼 스토리텔링과 초고속 체크아웃, 정기구독 빌링을 지원하는 프리미엄 브랜드 커머스입니다.',
    badge: '고전환 결제 UX',
  },
  {
    id: 'corporate',
    number: '06',
    name: '기업 랜딩 · 스타트업 · 브랜드 플래그십',
    engName: 'Corporate & Brand Flagship',
    description: '글로벌 투자 유치와 엔터프라이즈 수주를 이끄는 테크 스타트업 IR 랜딩, 상장사 및 중견기업 공식 플래그십 사이트입니다.',
    badge: '글로벌 IR 특화',
  },
];

export const GALLERY_PROJECTS: GalleryProject[] = [
  // ─── 01. 제조 (Manufacturing) ─────────────────────────────────
  {
    id: 'wonik-qnc-semiconductor-quartz',
    title: '원익큐앤씨 글로벌 No.1 쿼츠웨어 & 정밀 세라믹',
    client: '코스닥 상장사 (KOSDAQ: 074600) 원익큐앤씨',
    category: 'manufacturing',
    categoryName: '제조 · 반도체 소재부품',
    summary: '글로벌 쿼츠웨어 점유율 1위, 40주년 기념 영상 및 KOSDAQ 실시간 IR 허브',
    description: '반도체 식각·확산 공정 핵심 소재 쿼츠웨어 글로벌 1위 기업 원익큐앤씨의 공식 리뉴얼 프로토타입입니다. 4대 핵심 사업(쿼츠·세라믹·세정·옵틱) 인터랙티브 도면 및 쇼케이스, 40주년 기념 영상 상영관, KOSDAQ 실시간 주가 차트 및 SRM 신규 협력제안 포털을 탑재했습니다.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDgg1CFsX4Rlv7v8iswdosWchI-qMhyrD7vwnGmzOaR6P-3sCJD0XKtk3YCJebSRHSgrWQfTr1SQN79YTb7LobEF40hJaWrjcIyvbZyuxBi30x9cCYDsUv2XQsfpBCr_QHZ5qK1L1koYU4K9vg0r_8xrlGh9lhAfNHaUpRpM5KhGQ8Rfl3EBfuB-BbnFEs5Y1dunYaSmlNz5v4jkAwBK8m09fzboo4jrX0KCGkod1YWjeDPjqdaShEl',
    liveDemoUrl: '/demo/wonik-qnc',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', '40th PR Film', 'KOSDAQ IR Engine'],
    period: '3주',
    year: '2026',
    badge: '글로벌 1위 데모',
    highlights: [
      '300mm 웨이퍼 식각·확산 쿼츠웨어 글로벌 1위 4대 사업부 인터랙티브 쇼케이스',
      '40주년 기념 홍보 영상 극장 모달 및 UHD 챕터 네비게이션',
      'KOSDAQ(074600) 실시간 주가·시가총액·외국인보유율 & DART 전자공시 연동',
      'SRM 신규 협력사 제안, 공장 견학 예약, 글로벌 4개국어(KR/EN/CN/JP) 대응',
    ],
  },
  {
    id: 'hysfa-semiconductor-scada',
    title: '한양시스템 반도체 FA & 초고순도 가스 시스템',
    client: '삼성전자 세메스(SEMES) SSQ 인증 협력사',
    category: 'manufacturing',
    categoryName: '제조 · 반도체 장비',
    summary: '세메스(SEMES) SSQ 인증 협력사, 3대 사업부 쇼케이스 및 5단계 품질 파이프라인',
    description: '삼성전자 세메스 공식 협력사 한양시스템㈜의 반도체 공정 자동화(FA) 설비, 초고순도(UHP) 가스 공급 인프라 및 스마트 제어 S/W를 망라한 공식 웹사이트 프로토타입입니다. 27년 연혁, 5단계 전수 검사 QA 파이프라인 및 실시간 온라인 견적 접수 시스템을 탑재했습니다.',
    thumbnailUrl: '/hysfa/sub205_img01.jpg',
    liveDemoUrl: '/demo/hysfa',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', '5-Stage QA Pipeline', 'Bilingual (KR/EN)'],
    period: '4주',
    year: '2026',
    badge: 'SEMES SSQ 데모',
    highlights: [
      '반도체 FA 장비, 초고순도(UHP) 가스 배관 및 제어 S/W 3대 핵심 사업부 쇼케이스',
      '삼성전자 세메스(SEMES) SSQ 공식 품질인증 및 27년 연혁 인터랙티브 아카이브',
      '원자재 수입검사부터 헬륨 리크·72시간 신뢰성 시운전까지 5단계 전수 검사 파이프라인',
      '엔지니어링 온라인 견적 접수 위저드 채번 및 글로벌 다국어(KR/EN) 원클릭 전환',
    ],
  },
  {
    id: 'lithium-foil-spc',
    title: '리튬박 공정 데이터 모니터링 플랫폼',
    client: '2차전지 배터리 소재 제조사',
    category: 'manufacturing',
    categoryName: '제조 · 소재공정',
    summary: '슬리팅 롤 일지 입력 즉시 7대 불순물 통계 관리도와 4단계 로트 계보가 동기화되는 스마트 제조 플랫폼',
    description: '엑셀 수기 장부로 관리되던 리튬박 현장 일지를 웹 기반 실시간 엔터프라이즈 모니터링 시스템으로 전환했습니다. 7대 미량 불순물(Fe, Cu, Ni 등) ICP 통계 관리도(SPC), 12주 수율 워터폴 분석, 잉곳부터 슬리팅까지 완벽한 로트(Lot) 계보 역추적 엔진을 갖추고 있습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '/demo/lithium-foil',
    techStack: ['Next.js 16', 'React 19', 'TypeScript', 'Tailwind CSS v4', 'Custom SPC Charts'],
    period: '3주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      '12주 시뮬레이션 데이터 기반 실시간 통계 관리도 (Control Chart)',
      '슬리팅 현장 롤 일지 입력 즉시 전역 데이터 실시간 갱신',
      '잉곳-원료-슬리팅 4단계 로트(Lot) 계보 완벽 역추적',
      '관리한계선(USL/UCL) 자동 계산 및 불량 경보 알고리즘',
    ],
  },
  {
    id: 'cathode-mixing-scada',
    title: '2차전지 양극재 분체 배합 SCADA 시스템',
    client: '정밀 화학소재 엔터프라이즈',
    category: 'manufacturing',
    categoryName: '제조 · 스마트팩토리',
    summary: '고속 혼합기 8기 동시 계측 및 온도·압력·RPM 이상 감지 웹 관제 콘솔',
    description: '고용량 양극재 제조 라인의 분체 배합 공정을 초당 10회 고속 폴링하여 실시간 관리자 화면에 렌더링하는 엔터프라이즈 웹 대시보드입니다. 배치별 배합비 공차 초과 시 즉각 카카오 알림톡 및 경고 팝업을 발생시킵니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'WebSockets', 'Chart.js', 'PostgreSQL', 'Tailwind CSS'],
    period: '4주',
    year: '2025',
    badge: '대규모 관제',
    highlights: [
      '초당 10회 고속 데이터 스트리밍 렌더링',
      '8기 분체 믹서 실시간 상태 및 RPM 모니터링',
      '배치별 투입 원료 바코드 이력 추적',
      '이상 징후 발생 즉시 관리자 원격 비상 정지 트리거',
    ],
  },
  {
    id: 'semiconductor-clean-spc',
    title: '반도체 웨이퍼 세정 공정 SPC 통계 플랫폼',
    client: '반도체 전공정 부품사',
    category: 'manufacturing',
    categoryName: '제조 · 정밀전자',
    summary: '세정액 약액 농도 및 파티클 카운트 자동 분석 수율 관리 시스템',
    description: '클린룸 내 웨이퍼 세정 약품의 화학 조성비와 잔류 파티클 통계를 웨이퍼 랏(Lot) 단위로 실시간 수집하여, 공정 능력 지수(Cp, Cpk)를 자동 산출하는 웹 플랫폼입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Python FastAPI', 'TypeScript', 'Tailwind CSS', 'Highcharts'],
    period: '4주',
    year: '2025',
    badge: 'Cpk 수율 관리',
    highlights: [
      'Cpk 공정 능력 지수 실시간 자동 계산',
      '웨이퍼 랏별 파티클 히트맵 인터랙티브 뷰어',
      '케미컬 약액 교체 시점 예측 AI 알림',
    ],
  },
  {
    id: 'copper-foil-r2r',
    title: '동박 Roll-to-Roll 인라인 결함 감지 웹 뷰어',
    client: '초극박 동박 제조 전문기업',
    category: 'manufacturing',
    categoryName: '제조 · 롤투롤공정',
    summary: '초속 15m 고속 주행 롤 표면 핀홀 및 주름 실시간 좌표 맵핑 콘솔',
    description: '광학 비전 카메라 16대에서 전송되는 동박 표면 결함 좌표(X, Y, 면적)를 롤 길이 1,000m 단위로 웹 캔버스에 실시간 핀포인팅하여 재단 시 불량 구간을 자동 마킹합니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
    techStack: ['React', 'HTML5 Canvas', 'Tailwind CSS', 'TypeScript', 'Node.js'],
    period: '3주',
    year: '2025',
    badge: '인라인 비전',
    highlights: [
      'HTML5 고성능 캔버스 기반 초당 60fps 결함 맵핑',
      '핀홀·스크래치·주름 결함 유형별 필터링',
      '슬리팅 재단 최적화 컷팅 플랜 자동 생성',
    ],
  },
  {
    id: 'press-molding-iot',
    title: '자동차 부품 정밀 프레스 사출 IoT 모니터링',
    client: '티어1 자동차 샤시 부품사',
    category: 'manufacturing',
    categoryName: '제조 · 프레스가공',
    summary: '금형 온도 편차 및 프레스 타격 하중 톤수 실시간 계측 모니터링',
    description: '1,200톤 프레스 설비 6기의 타격 하중 센서와 금형 온도 데이터를 연동하여, 금형 마모와 크랙을 사전에 방지하는 예지 정비 대시보드를 구축했습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'MQTT', 'Chart.js'],
    period: '3주',
    year: '2024',
    badge: 'IoT 예지정비',
    highlights: [
      '하중 로드셀 센서 실시간 피크 톤수 트래킹',
      '금형 수명 타수 카운터 및 마모 주기 예측',
      '작업자별 생산 목표치 대비 실시간 달성률 게이지',
    ],
  },
  {
    id: 'chemical-reactor-portal',
    title: '정밀화학 배치 반응기 제어 & 생산 이력 포털',
    client: '특수 기능성 폴리머 제조사',
    category: 'manufacturing',
    categoryName: '제조 · 화학플랜트',
    summary: '반응조 12기 승온·냉각 사이클 실시간 기록 및 시험성적서 자동 발행',
    description: '화학 반응조별 교반 속도, 승온 프로파일, 압력 변화를 디지털 레코더로 자동 기록하고 출하 시험 성적서(COA)를 원클릭 PDF로 자동 생성합니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'TypeScript', 'PDFKit', 'Tailwind CSS', 'PostgreSQL'],
    period: '4주',
    year: '2024',
    badge: 'COA 성적서 자동화',
    highlights: [
      '반응 프로파일 타임라인 비교 오버레이',
      'COA 시험성적서 원클릭 PDF 자동 발행',
      '화학물질관리법(화관법) 준수 로그 저장',
    ],
  },

  // ─── 02. 인테리어 (Interior) ─────────────────────────────────
  {
    id: 'atelier-vaucluse',
    title: '아뜰리에 보클루즈 (ATELIER VAUCLUSE)',
    client: '건축 · 인테리어 디자인 스튜디오',
    category: 'interior',
    categoryName: '인테리어 · 건축',
    summary: '미니멀 세리프와 자연석 샌드 웜톤의 프렌치 모더니즘 하이엔드 건축·인테리어 스튜디오 웹사이트',
    description: '화려한 치장보다 천연 트래버틴과 미장 회벽, 훈증 오크의 물성을 앞세운 최고급 건축 인테리어 에이전시의 브랜드 웹사이트입니다. 공간 철학 3대 축 소개, 반응형 프로젝트 아카이브 및 필터링, 1:1 프라이빗 공간 컨설팅 예약 위저드 시스템을 탑재했습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '/demo/atelier-vaucluse',
    techStack: ['Next.js 16', 'Tailwind CSS v4', 'TypeScript', 'Editorial Grid', 'Modal Booking'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      '공간 철학 및 4단계 건축 프로세스 인터랙션',
      '고해상도 건축 프로젝트 갤러리 & 동적 필터',
      '프라이빗 1:1 고객 상담 예약 위저드',
      '천연 트래버틴/오크 등 마감재 디지털 라이브러리',
    ],
  },
  {
    id: 'hannam-penthouse',
    title: '한남 더 힐 펜트하우스 주거 공간 아카이브',
    client: '하이엔드 프라이빗 인테리어 랩',
    category: 'interior',
    categoryName: '인테리어 · 주거공간',
    summary: '빛과 그림자의 여백을 담은 최고급 100평형 펜트하우스 시공 포트폴리오',
    description: '도심 속 안식처를 지향하는 최고급 펜트하우스 전용 포트폴리오 사이트로, 시공 전 3D 렌더링과 완공 후 8K 실물 사진을 인터랙티브 슬라이더로 비교 감상할 수 있습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'Image Compare Slider'],
    period: '2주',
    year: '2025',
    badge: '럭셔리 주거',
    highlights: [
      'Before & After 시공 전후 비교 인터랙티브 슬라이더',
      '수입 주방가구 및 조명 스펙 인터랙티브 핀 마킹',
      '공간별 파노라마 360 가상 투어 뷰어 연동',
    ],
  },
  {
    id: 'seongsu-flagship-showroom',
    title: '성수 플래그십 쇼룸 & 복합문화공간 디자인',
    client: '공간 브랜딩 크리에이티브 그룹',
    category: 'interior',
    categoryName: '인테리어 · 상업공간',
    summary: '노출 콘크리트와 스틸, 식생의 조화를 담은 상업 공간 브랜딩 웹사이트',
    description: '브랜드 팝업과 플래그십 쇼룸을 전문으로 설계하는 스튜디오의 프로젝트 아카이브로, 공간 기획부터 브랜드 아이덴티티, 가구 제작까지의 전 과정을 매거진 스타일로 소개합니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'Framer Motion', 'TypeScript'],
    period: '2주',
    year: '2025',
    badge: '상업 공간 브랜딩',
    highlights: [
      '매거진 스타일 에디토리얼 레이아웃',
      '공간별 방문객 동선 인터랙티브 맵',
      '클라이언트 브랜드 협업 히스토리 쇼케이스',
    ],
  },
  {
    id: 'bundang-workspace',
    title: '테크 스타트업 분당 사옥 스마트 오피스',
    client: '오피스 전문 인테리어 그룹',
    category: 'interior',
    categoryName: '인테리어 · 업무공간',
    summary: '몰입과 협업을 유도하는 500석 규모 IT 기업 사옥 공간 설계 포트폴리오',
    description: '하이브리드 워크 환경을 고려한 폰부스, 라운지, 타운홀 미팅 공간의 음향 흡음 설계와 조도 제어 시스템을 인터랙티브하게 안내하는 웹사이트입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript'],
    period: '2주',
    year: '2025',
    badge: '스마트 오피스',
    highlights: [
      '500석 규모 층별 공간 조닝 다이어그램 인터랙션',
      '모듈형 회의실 예약 키오스크 UI 목업 연동',
      '친환경 LEED 인증 자재 아카이브',
    ],
  },
  {
    id: 'jeju-stone-stay',
    title: '제주 애월 돌담 프리미엄 독채 스테이',
    client: '스테이 기획 & 건축 디자인 랩',
    category: 'interior',
    categoryName: '인테리어 · 숙박공간',
    summary: '제주 현무암과 노천 히노끼탕의 감성을 담은 부티크 스테이 브랜드 웹',
    description: '제주 자연을 온전히 담아낸 독채 풀빌라의 공간 포트폴리오로, 실시간 객실 예약 시스템 연동 및 계절별 채광 변화를 영상으로 담아냈습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'Booking API'],
    period: '2주',
    year: '2024',
    badge: '부티크 스테이',
    highlights: [
      '감성적 비디오 백그라운드 스트리밍',
      '객실별 실시간 예약 캘린더 연동',
      '주변 제주 로컬 명소 큐레이션 지도',
    ],
  },
  {
    id: 'cheongdam-beauty-lounge',
    title: '청담동 프라이빗 웰니스 & 뷰티 라운지',
    client: '뷰티 메디컬 인테리어 스튜디오',
    category: 'interior',
    categoryName: '인테리어 · 뷰티/의료',
    summary: '곡면 미장벽과 간접 조명으로 완성한 프라이빗 VIP 케어 공간',
    description: '철저한 프라이버시 보호를 위한 1인 VIP 룸 동선 분리와 무영등 조도 설계를 강조한 하이엔드 뷰티 메디컬 공간 프로젝트입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript'],
    period: '2주',
    year: '2024',
    badge: 'VIP 프라이빗',
    highlights: [
      '곡선형 벽체 시공 공법 상세 소개',
      '1인 VIP 케어룸 동선 설계 시뮬레이션',
      '상담 예약 폼과 카카오 채널 실시간 연동',
    ],
  },

  // ─── 03. 건축 (Architecture) ─────────────────────────────────
  {
    id: 'sodamjae-hanok-architecture',
    title: '소담재 건축공방 전통한옥 & 프리미엄 중목구조',
    client: '국가유산 수리기능자 도편수 직영 목수단',
    category: 'architecture',
    categoryName: '건축 · 현대한옥/주거',
    summary: '25년 도편수 직영 전통 결구(사개맞춤) 공법과 패시브 삼중창호 단열을 융합한 프리미엄 한옥 스튜디오',
    description: '100년 목재 자연 건조 노하우, 못을 쓰지 않는 전통 사개맞춤 결구의 구조미 위에 최고 등급 시스템 삼중창호와 현대식 지열·단열 설비를 더한 프리미엄 한옥 건축공방의 공식 웹사이트입니다. 전국 68채 완공작 아카이브, 도편수 철학, 5단계 시공 로드맵 및 1:1 맞춤 견적 신청 위저드를 탑재했습니다.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD_PpesrIFiVF4zFREwOcLQM-SdxMeXTGAlM4AyMaAoLdhb74A4OKHLdKt9pUUP3z3nC2X_KhhWnEiuwJGcSlpR-5ef2HRqfaH_NB1IcqNJ4vNb1cLwIZqky5fCAGw_W4fEiHUnp8ge4_PwWE6n4VnhpaBVzSQTSkhfKK1yGN8oSNYskPPkvhtu3U_iFDeeKw00xfMkhiRtfo3xoQXQaKCZf1gcQIXga3ukOvVNTCKbMgfQQwJ2MJVH',
    liveDemoUrl: '/demo/sodamjae',
    techStack: ['Next.js 16', 'React 19', 'Tailwind CSS v4', 'TypeScript', 'Project Detail Modal', 'Hanok Quote Wizard'],
    period: '2주',
    year: '2026',
    badge: '실물 라이브 데모',
    highlights: [
      '국가유산 수리기능자 도편수 직영 68+ 완공 한옥 아카이브 & 상세 모달',
      '전통 결구(사개맞춤) 공법 & 현대 패시브 단열 하이브리드 설계 인터랙션',
      '실시간 한옥 건축 상담 및 1:1 맞춤 견적 가이드 접수 위저드',
      '단독 살림집·별서 세컨하우스·도심형 한옥 카테고리별 동적 필터링',
    ],
  },
  {
    id: 'general-construction-corp',
    title: '종합건설사 디지털 포트폴리오 & 수주 브로슈어',
    client: '도급 순위 중견 종합건설기업',
    category: 'architecture',
    categoryName: '건축 · 종합건설',
    summary: '관급 토목부터 대형 상업 복합빌딩까지 50여 건의 시공 실적 디지털 아카이브',
    description: '관급 공사 입찰 및 민간 개발 수주 심사에 최적화된 종합건설사의 공식 포트폴리오 웹사이트입니다. 공사 규모, 완공일, 발주처, 특허 공법별 실시간 필터링과 원클릭 실적증명서 다운로드를 지원합니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'Search & Filter Engine'],
    period: '3주',
    year: '2025',
    badge: '수주 특화 웹',
    highlights: [
      '50여 건 대형 시공 실적 카테고리별 다이내믹 필터링',
      '발주처 제출용 고해상도 PDF 브로슈어 생성',
      '주요 특허 공법 및 안전보건경영시스템(ISO) 인증관',
    ],
  },
  {
    id: 'modern-timber-residence',
    title: '모던 중목구조 주택 & 전원 단지 시공 브랜드',
    client: '프리미엄 목조주택 전문 시공사',
    category: 'architecture',
    categoryName: '건축 · 주택시공',
    summary: '내진 1등급 친환경 독일식 목조주택 공법 소개 및 3D 모델하우스 투어',
    description: '일본 중목 가공 프리컷(Pre-cut) 정밀 공법과 독일식 패시브 창호 기술을 적용한 단독주택 브랜드 사이트로, 단지별 분양 안내 및 3D 모델하우스 가상 뷰어를 탑재했습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Three.js / WebGL', 'Tailwind CSS', 'TypeScript'],
    period: '3주',
    year: '2025',
    badge: '3D 가상 투어',
    highlights: [
      'WebGL 기반 3D 주택 단면 구조 분해도',
      '단지별 잔여 필지 실시간 분양 현황판',
      '건축주 맞춤형 시공비 견적 시뮬레이터',
    ],
  },
  {
    id: 'logistics-plant-engineering',
    title: '대형 저온물류센터 & 플랜트 엔지니어링 실적 웹',
    client: '산업 플랜트 엔지니어링 그룹',
    category: 'architecture',
    categoryName: '건축 · 물류/플랜트',
    summary: '연면적 3만 평 규모 자동화 물류창고 및 냉동 플랜트 시공 테크 웹사이트',
    description: '초저온 단열 공법과 바닥 평탄도(Superflat Floor) 시공 기술력을 해외 화주 및 자산운용사에 어필할 수 있는 영문/국문 듀얼 테크니컬 쇼케이스입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'i18n Multi-language', 'Tailwind CSS', 'TypeScript'],
    period: '3주',
    year: '2025',
    badge: '플랜트 테크',
    highlights: [
      '국문/영문 다국어 원클릭 스위칭',
      '바닥 평탄도(F-number) 계측 데이터 시각화',
      '친환경 물류센터 BREEAM 인증 실적 소개',
    ],
  },
  {
    id: 'atelier-arch-firm',
    title: '하이엔드 단독주택 건축사사무소 아카이브',
    client: '건축문화대상 수상 건축사사무소',
    category: 'architecture',
    categoryName: '건축 · 설계사무소',
    summary: '자연 경관과의 대화를 담은 15개 명작 단독주택 건축 아카이브',
    description: '건축 도면의 엄격한 비례감과 사진작가의 흑백/컬러 화보를 조화롭게 배치한 건축사사무소 공식 웹사이트입니다. 설계 의도와 모형 제작 과정이 수록되어 있습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'Minimalist Gallery'],
    period: '2주',
    year: '2024',
    badge: '건축대상 수상작',
    highlights: [
      '건축 평면도-입면도 인터랙티브 오버레이',
      '건축 모형 360 회전 인터랙티브 뷰어',
      '출판 서적 및 학술 논문 아카이브',
    ],
  },
  {
    id: 'civil-bridge-engineering',
    title: '교량·터널 특수 토목 엔지니어링 웹사이트',
    client: '특수 교량 설계 전문 엔지니어링사',
    category: 'architecture',
    categoryName: '건축 · 토목기술',
    summary: '사장교·현수교 케이블 진동 제어 및 내진 보강 특허 기술 소개',
    description: '국내외 100여 개 교량 안전진단과 내진 보강 실적을 보유한 토목 엔지니어링 기업의 기술 신뢰도를 극대화한 인터랙티브 웹사이트입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript'],
    period: '3주',
    year: '2024',
    badge: '특수 교량 공법',
    highlights: [
      '지진파 시뮬레이션 인터랙티브 애니메이션',
      '전국 교량 시공 실적 지도(Map) 연동',
      '특허 기술 시방서 열람 시스템',
    ],
  },
  {
    id: 'urban-regeneration-reno',
    title: '성수·문래 폐공장 도시재생 리노베이션 아카이브',
    client: '도시재생 전문 건축 그룹',
    category: 'architecture',
    categoryName: '건축 · 리모델링',
    summary: '붉은 벽돌과 철골 트러스를 보존하며 신축 이상의 가치를 만든 재생 건축',
    description: '기존 건축물의 역사적 유산을 보존하면서 현대적 내진/단열 보강을 완료한 도시재생 프로젝트를 스토리텔링 방식으로 풀어낸 디지털 포트폴리오입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript'],
    period: '2주',
    year: '2024',
    badge: '도시재생 실적',
    highlights: [
      '1970년대 원형 공장과 현재 재생 공간의 비교 기록',
      '건축물 안전진단 등급 상향 과정 투명 공개',
      '관할 지자체 도시재생 대상 수상 소개',
    ],
  },

  // ─── 04. SAAS (B2B SaaS) ─────────────────────────────────
  {
    id: 'tdocs-legal-saas',
    title: 'T-DOCS (티독스) - 카카오 10초 전자서명 SaaS',
    client: '주식회사 태문 직영 SaaS',
    category: 'saas',
    categoryName: 'SaaS · 전자서명',
    summary: '300여 종 산업 서식 지면 에디터와 카톡 모바일 10초 전자서명 플랫폼',
    description: '건축, 인테리어, 부동산, 일반 기업 실무에 필수적인 300여 종의 전문 서식을 웹 에디터로 실시간 작성하고, 카카오 알림톡으로 전송하여 1분 만에 전자서명을 체결하는 올인원 스마트 도큐먼트 플랫폼입니다. 전자서명법 제3조 준수 감사추적증명서가 발급됩니다.',
    thumbnailUrl: '/images/mockup_tdocs.jpg',
    externalUrl: 'https://tdocs.kr',
    techStack: ['Next.js', 'React', 'Supabase RLS', 'PortOne V2', 'SOLAPI Alimtalk', 'Vector PDF'],
    period: '4주',
    year: '2026',
    badge: '직영 운영 서비스',
    highlights: [
      '300여 종 전문 서식 반응형 지면 프리뷰 에디터',
      '카카오톡 원클릭 전자서명 및 감사추적 증명서 발급',
      'PDF 벡터 엔진 기반 타임스탬프 위변조 방지',
      '정기 구독 빌링 및 포인트 복합 결제 시스템',
    ],
  },
  {
    id: 'taemun-bridge-platform',
    title: '태문브릿지 - 건축·설비 B2B 매칭 & 안심정산',
    client: '주식회사 태문 직영 플랫폼',
    category: 'saas',
    categoryName: 'SaaS · B2B 플랫폼',
    summary: '산업 엔지니어링 매칭 및 에스크로 기반 단계별 기성 검수 정산 시스템',
    description: '건축, 인테리어, 기계설비 분야의 의뢰인과 검증된 전문 시공팀을 연결하는 B2B 플랫폼입니다. 7단계 견적-계약-검수-정산 라이프사이클 관리와 PASS 본인인증, 투명한 단계별 에스크로 정산 체계를 지원합니다.',
    thumbnailUrl: '/images/mockup_taemun_bridge.jpg',
    externalUrl: 'https://taemun.co.kr',
    techStack: ['Next.js', 'Supabase RLS', 'PortOne PASS', 'Tailwind CSS', 'Admin CMS'],
    period: '6주',
    year: '2025',
    badge: '직영 운영 서비스',
    highlights: [
      '7단계 견적-계약-검수-정산 라이프사이클 엔진',
      'PASS 본인인증 및 안전한 기성 정산 모듈',
      '전문가 프로필 및 실적 포트폴리오 관리 시스템',
      '견적 상태 변경 카카오 알림톡 자동 통보',
    ],
  },
  {
    id: 'smart-quote-crm',
    title: '산업 맞춤형 자동 견적 산출기 & 고객 CRM',
    client: '인테리어 자재 유통 B2B 기업',
    category: 'saas',
    categoryName: 'SaaS · 견적자동화',
    summary: '평형·자재별 실시간 단가 자동 계산 및 계약서 원클릭 생성 CRM',
    description: '고객이 웹에서 면적, 자재 스펙, 시공 항목을 선택하면 3초 만에 상세 내역서와 견적서 PDF가 생성되고 영업 담당자에게 리드가 자동 배정되는 B2B 세일즈 자동화 솔루션입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Supabase', 'PDF Generator'],
    period: '3주',
    year: '2025',
    badge: '세일즈 자동화',
    highlights: [
      '면적·공종별 실시간 시공비 자동 계산 엔진',
      '견적서 원클릭 PDF 출력 및 고객사 이메일 발송',
      '영업 파이프라인 단계별 칸반 보드 CRM',
    ],
  },
  {
    id: 'field-work-daily-log',
    title: '건설 현장 모바일 작업일보 & 자재 수불 SaaS',
    client: '전문건설업체 20개사 연합',
    category: 'saas',
    categoryName: 'SaaS · 현장관리',
    summary: '스마트폰 사진 촬영으로 완료되는 노무 투입 공수 및 자재 입출고 관리',
    description: '현장 소장이 스마트폰으로 공종별 출력 인원과 자재 입고 사진을 등록하면 본사 공사팀 ERP로 실시간 집계되는 현장 밀착형 모바일 웹앱입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js PWA', 'Tailwind CSS', 'Supabase Storage', 'TypeScript'],
    period: '3주',
    year: '2025',
    badge: '모바일 PWA',
    highlights: [
      '오프라인 상태에서도 작성 가능한 PWA 캐싱',
      '공종별 인력 투입 공수(M/D) 자동 정산',
      '본사 ERP 연동 자재 입출고 수불부 자동 집계',
    ],
  },
  {
    id: 'labor-contract-payroll',
    title: '일용직 근로계약서 & 4대보험 급여 계산 SaaS',
    client: '인력 공급 및 파견 전문 기업',
    category: 'saas',
    categoryName: 'SaaS · 인사노무',
    summary: '모바일 전자근로계약서 체결 및 일급·주휴수당·소득세 자동 계산',
    description: '건설·물류 현장 일용직 근로자의 출역 기록을 기반으로 법정 일용근로계약서를 카카오 알림톡으로 자동 서명하고, 4대보험 공제 후 실지급액을 산출하는 노무 자동화 플랫폼입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'PostgreSQL', 'SOLAPI', 'TypeScript', 'Tailwind CSS'],
    period: '4주',
    year: '2024',
    badge: '급여 자동정산',
    highlights: [
      '전자서명법 준수 일용근로계약서 카톡 원클릭 체결',
      '국세청 일용근로소득 지급명세서 전산 매체 파일 생성',
      '신분증 진위 확인 및 통장사본 OCR 자동 인식',
    ],
  },
  {
    id: 'b2b-order-procurement',
    title: '기업 간 자재 B2B 발주 및 전자세금계산서 포털',
    client: '산업 설비 부자재 유통사',
    category: 'saas',
    categoryName: 'SaaS · 구매발주',
    summary: '거래처별 전용 단가표 적용 및 홈택스 전자세금계산서 자동 발행 연동',
    description: '300여 거래처가 각자의 할인율이 적용된 단가표로 웹 발주를 진행하고, 출고 완료 시 국세청 홈택스 전자세금계산서가 자동 역발행되는 올인원 B2B 구매 플랫폼입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Supabase', 'Popbill API', 'TypeScript', 'Tailwind CSS'],
    period: '4주',
    year: '2024',
    badge: '발주-세금계산서',
    highlights: [
      '거래처별 맞춤형 단가표 및 여신 한도 관리',
      '팝빌 API 연동 국세청 전자세금계산서 1초 발행',
      '품목별 재고 부족 시 공급사 자동 발주 알림',
    ],
  },

  // ─── 05. 쇼핑몰 커머스 (Commerce) ─────────────────────────────────
  {
    id: 'organic-ceramic-living',
    title: '오가닉 세라믹 & 리빙 오브제 D2C 셀렉트숍',
    client: '도예 작가 공예 브랜드',
    category: 'commerce',
    categoryName: '커머스 · 리빙/오브제',
    summary: '핸드크래프트 도자기와 자연 소재 홈웨어 큐레이션 프리미엄 D2C 스토어',
    description: '작가의 흙과 유약에 대한 철학을 고해상도 비주얼 화보로 담아낸 감성 커머스입니다. 포트원 간편결제(네이버페이, 카카오페이, 토스), 실시간 재고 품절 동기화, 선물하기 기능을 탑재했습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1615529182904-14819c35db37?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'PortOne V2 Pay', 'Tailwind CSS', 'TypeScript', 'Supabase'],
    period: '2주',
    year: '2025',
    badge: '간편결제 완비',
    highlights: [
      '네이버페이 · 카카오페이 · 토스페이 원클릭 결제',
      '주문 제작 작품별 맞춤 이니셜 각인 옵션 위저드',
      '카카오 알림톡 배송 조회 및 카카오 선물하기 연동',
    ],
  },
  {
    id: 'techwear-outdoor-gear',
    title: '프리미엄 테크웨어 & 아웃도어 기어 플래그십',
    client: '테크니컬 기능성 어패럴 브랜드',
    category: 'commerce',
    categoryName: '커머스 · 패션/아웃도어',
    summary: '고밀도 방수 원단 3D 뷰어와 드롭(Drop) 래플 추첨 한정판 커머스',
    description: '고기능성 방수/투습 원단의 질감을 줌인 뷰어로 감상하고, 한정판 발매 시 서버 다운 없는 대용량 트래픽 래플 추첨 시스템을 갖춘 스트리트 테크웨어 스토어입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'Redis', 'TypeScript', 'PortOne'],
    period: '3주',
    year: '2025',
    badge: '한정판 드롭',
    highlights: [
      '한정판 출시 시 초당 1만 건 동시 접속 래플 대기열',
      '원단 방수 성능 테스트 영상 인터랙티브 쇼케이스',
      '체형별 사이즈 추천 알고리즘 탑재',
    ],
  },
  {
    id: 'specialty-coffee-sub',
    title: '스페셜티 로스터리 커피 원두 정기구독 숍',
    client: '성수 로스터리 카페 브랜드',
    category: 'commerce',
    categoryName: '커머스 · 식품/구독',
    summary: '취향 테스트 기반 싱글오리진 원두 격주 자동결제 빌링 구독 서비스',
    description: '산미, 바디감, 향미 5문항 취향 테스트 결과에 맞춰 매주 갓 볶은 싱글오리진 원두를 정기 배송하는 구독 커머스입니다. 빌링키 자동 결제 및 구독 일시정지 기능을 지원합니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'PortOne BillingKey', 'Tailwind CSS', 'TypeScript'],
    period: '2주',
    year: '2025',
    badge: '정기구독 빌링',
    highlights: [
      '5문항 커피 테이스트 큐레이션 알고리즘',
      '카드 빌링키 기반 격주/매월 자동 반복 결제',
      '원클릭 구독 주기 변경 및 휴가철 건너뛰기 기능',
    ],
  },
  {
    id: 'vegan-skincare-d2c',
    title: '비건 클린뷰티 & 천연 에센셜 스킨케어 스토어',
    client: '자연주의 화장품 스타트업',
    category: 'commerce',
    categoryName: '커머스 · 뷰티/헬스',
    summary: '전 성분 EWG 그린 등급 공개 및 피부 타입별 루틴 추천 반응형 숍',
    description: '화려한 화학 성분 대신 제주 유기농 식물 추출물을 전면에 내세운 비건 스킨케어 브랜드 웹사이트로, 피부 고민별 3단계 케어 루틴 번들 구매 할인 시스템을 탑재했습니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'PortOne V2'],
    period: '2주',
    year: '2024',
    badge: 'EWG 성분 사전',
    highlights: [
      'EWG 그린 등급 원료 백과사전 팝업 연동',
      '번들 세트 구성 시 실시간 추가 할인 계산기',
      '포토 리뷰 작성 시 적립금 자동 지급 모듈',
    ],
  },
  {
    id: 'handcrafted-leather-goods',
    title: '핸드메이드 베지터블 가죽 가방 & 커스텀 오더 숍',
    client: '가죽 공방 아뜰리에',
    category: 'commerce',
    categoryName: '커머스 · 가죽/잡화',
    summary: '이태리 베지터블 가죽 에이징 스토리와 실시간 가죽·실 컬러 시뮬레이터',
    description: '시간이 지날수록 깊어지는 가죽의 멋을 영상으로 보여주고, 고객이 직접 본체 가죽, 안감, 스티치 색상을 선택하면 실시간 렌더링되는 비스포크 커스텀 주문 숍입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'Canvas Customizer'],
    period: '2주',
    year: '2024',
    badge: '커스텀 시뮬레이터',
    highlights: [
      '가죽·실·황동 금속 버클 실시간 컬러 조합기',
      '에이징 1년/3년/5년 경과 변화 타임랩스',
      '공방 장인의 재단 및 새들 스티치 제작기 수록',
    ],
  },
  {
    id: 'kitchenware-curation-store',
    title: '미니멀 스테인리스 키친웨어 셀렉트 스토어',
    client: '주방 식기 큐레이션 브랜드',
    category: 'commerce',
    categoryName: '커머스 · 주방/쿡웨어',
    summary: '위생적인 304 스테인리스 조리도구 및 테이블웨어 컬렉션 숍',
    description: '전문 셰프의 주방을 연상시키는 정갈한 메탈릭 감성의 식기 쇼핑몰로, 요리 레시피별 사용 조리도구 원클릭 세트 장바구니 담기 기능을 지원합니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'PortOne V2'],
    period: '2주',
    year: '2024',
    badge: '레시피 연계 구매',
    highlights: [
      '셰프 레시피 콘텐츠 연계 원클릭 도구 세트 구매',
      '스테인리스 첫 세척 연마제 제거 가이드 영상',
      '인덕션/식기세척기 호환성 직관적 아이콘 표기',
    ],
  },

  // ─── 06. 기업 랜딩 (Corporate) ─────────────────────────────────
  {
    id: 'ai-robotics-deeptech-ir',
    title: '물류 자율주행 AI 로보틱스 스타트업 IR & 공식 웹',
    client: '시리즈 B AI 모빌리티 기업',
    category: 'corporate',
    categoryName: '기업랜딩 · AI/딥테크',
    summary: '자율주행 AMR 로봇 주행 기술력과 국내외 15개사 고객사 도입 실적 IR 사이트',
    description: '글로벌 벤처 캐피탈 투자 유치와 대기업 공급 계약 체결을 이끌어낸 딥테크 스타트업의 공식 플래그십 사이트입니다. 라이다 센서 인지 영상과 물류창고 도입 효과 ROI 계산기를 제공합니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'Interactive ROI Calculator'],
    period: '2주',
    year: '2025',
    badge: '시리즈B 투자유치',
    highlights: [
      '물류창고 면적별 인건비 절감액 ROI 인터랙티브 계산기',
      'AMR 로봇 군집 제어 관제 알고리즘 테크 백서 다운로드',
      '글로벌 IR 피치덱 보안 열람 및 NDA 동의 연동',
    ],
  },
  {
    id: 'cleantech-renewable-energy',
    title: '차세대 친환경 수소·태양광 에너지 엔터프라이즈',
    client: '신재생에너지 상장 중견기업',
    category: 'corporate',
    categoryName: '기업랜딩 · 클린테크',
    summary: 'ESG 경영 지표 공개 및 전국 40개 발전소 실시간 발전량 통계 연동',
    description: '글로벌 RE100 기준에 맞춘 수소 연료전지 및 해상 풍력 발전 사업 현황을 실시간 발전량 API와 연계하여 보여주는 친환경 에너지 대기업 공식 사이트입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'API Integration'],
    period: '3주',
    year: '2025',
    badge: 'ESG 경영 공시',
    highlights: [
      '전국 발전소 실시간 누적 탄소 감축량 카운터',
      '지속가능경영 보고서 및 공시 정보 자동 동기화',
      '사업장별 환경 인허가 및 ISO14001 인증 현황',
    ],
  },
  {
    id: 'venture-capital-portfolio',
    title: '초기 테크 스타트업 전문 벤처캐피탈 공식 웹',
    client: '테크 전문 AC / VC 펀드',
    category: 'corporate',
    categoryName: '기업랜딩 · VC/투자',
    summary: '운용 자산 1,500억 및 80여 개 포트폴리오사 인터랙티브 투자 아카이브',
    description: '창업팀의 IR 덱 접수 파이프라인과 80개 포트폴리오사의 후속 투자 유치 현황, 파트너 심사역 전문 분야를 명확하게 제시하는 프리미엄 VC 공식 사이트입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript'],
    period: '2주',
    year: '2025',
    badge: '투자 포트폴리오',
    highlights: [
      '80개 투자사 분야별(AI, 바이오, 커머스) 필터링',
      '스타트업 사업계획서 접수 위저드 및 심사 알림',
      '분기별 투자 리포트 및 인사이트 뉴스레터 발송',
    ],
  },
  {
    id: 'bio-health-research-lab',
    title: '항암 면역 바이오텍 연구소 혁신 기술 웹',
    client: '코스닥 기술특례 상장 준비 바이오텍',
    category: 'corporate',
    categoryName: '기업랜딩 · 바이오헬스',
    summary: '신약 후보물질 파이프라인 진행 단계(임상 1상/2상) 인터랙티브 현황판',
    description: '글로벌 제약사 기술 수출(L/O)을 목표로, 표적 단백질 분해(TPD) 신약 파이프라인의 작용 기전과 전임상/임상 데이터 진행도를 투명하게 시각화한 바이오 연구소 웹사이트입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'Interactive Pipeline'],
    period: '3주',
    year: '2024',
    badge: '신약 파이프라인',
    highlights: [
      '후보물질별 임상 단계(디스커버리~임상2상) 트래커',
      '국제 학술지 논문 게재 및 특허 등록 현황 아카이브',
      '기술 이전(L/O) 제휴 미팅 신청 폼 연동',
    ],
  },
  {
    id: 'global-supply-logistics-corp',
    title: '글로벌 항공·해상 물류 SCM 공급망 기업 공식 웹',
    client: '포워딩 및 3PL 전문 복합물류사',
    category: 'corporate',
    categoryName: '기업랜딩 · 복합물류',
    summary: '전 세계 28개국 거점 네트워크 및 B/L 화물 위치 실시간 트래킹 포털',
    description: '해상/항공 컨테이너 운송 선적 화물의 선하증권(B/L) 번호 입력 시 현 위치와 통관 예정일을 즉시 조회할 수 있는 종합 물류 포워딩 기업의 공식 웹사이트입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'Tracking API'],
    period: '3주',
    year: '2024',
    badge: '화물 위치 트래킹',
    highlights: [
      'B/L 및 컨테이너 번호 기반 실시간 화물 위치 추적',
      '전 세계 28개국 지사 위치 인터랙티브 인터내셔널 맵',
      '해상/항공 수출입 운임 실시간 견적 요청 시스템',
    ],
  },
  {
    id: 'fintech-solution-portal',
    title: '글로벌 해외송금 & 환헤지 핀테크 엔터프라이즈',
    client: '기획재정부 등록 외환 핀테크사',
    category: 'corporate',
    categoryName: '기업랜딩 · 핀테크',
    summary: '수출입 기업을 위한 실시간 환율 계산 및 외환 안심 결제 소개 웹',
    description: '시중 은행 대비 80% 저렴한 환전 수수료와 환율 변동 리스크 헷지 솔루션을 수출입 무역 기업에 제안하는 금융 보안 준수 기업 웹사이트입니다.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80',
    techStack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'Real-time FX Rates'],
    period: '2주',
    year: '2024',
    badge: '금융 보안 준수',
    highlights: [
      '주요 통화(USD, EUR, JPY, CNY) 실시간 환율 계산기',
      '금융감독원 보안성 심의 통과 인증 마크 및 감사 보고서',
      '수출입 기업 전용 가상계좌 개설 안내 시스템',
    ],
  },
];
